### ISSUE TITLE
[Question] How to set sql dialect for timescale?

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#10045]
**Component**

 * Generic

**Description**
I need to query data from timeserial with json type. Like this:
```sql
@Query(value = "SELECT a.* FROM author a "
            + "WHERE CAST(a.book ->> 'price' AS INTEGER) = ?1",
            nativeQuery = true)
```
But it turned out an error: 
```text
No Dialect mapping for JDBC type: 1111; nested exception is org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
```

Then i add config in application.yml
```yml
spring:
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
```
But it doesn't work.

**Environment**

 * OS:  mac && windows && linux
 * ThingsBoard: 3.4.2-SNAPSHOT
 * Browser:
