### ISSUE TITLE
 The API for the entity query controller is returning empty keys, despite the presence of telemetry keys.

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard#10298]
**Describe the bug**
I have configured the docker-compose file so that Postgres and Cassandra DB are running outside the docker container. API Under entity-query-controller  ```  /api/entitiesQuery/find/keys{?attributes,timeseries}  ``` returns an empty list even though telemetry keys are present.

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard Version:- tb-cassandra:latest
  * Community 

**docker-compose file **
```
version: '3.0'
services:
  thingsboard:
    restart: unless-stopped
    image: "thingsboard/tb-cassandra:latest"
    expose:
      - "80"
    ports:
      - "80:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      DATABASE_TS_TYPE: cassandra
      DATABASE_TS_LATEST_TYPE: cassandra
      CASSANDRA_URL: cassandra:9042
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
    volumes:
      - /path/data:/data
      - /path/logs:/var/log/thingsboard
    links:
      - postgres
      - cassandra
    depends_on:
      - postgres
      - cassandra  
  postgres:
    restart: unless-stopped
    image: "postgres:12"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - /path/data/db
  cassandra:
    restart: unless-stopped
    image: "cassandra:4.0.4"
    ports:
      - "9042"
    volumes:
      - /path/data/cassandra
```

**Additional context**
When Postgres and Cassandra are inside the docker container able to get the telemetry keys, but with this configuration not able to get the keys. 
When we checked whether the data was getting stored in Cassandra, we could see the ts_kv_cf table which had telemetry data.

please guide us to resolve this issue.
