### ISSUE TITLE
Rule engine `RECEIVED INVALID MESSAGE` error, what does it mean?

### ISSUE THREAD

**Issue by sprijk** [thingsboard/thingsboard#10638]
**Component**
 * Rule Engine

**Description**
* Using ThingsBoard Microservices Architecture
* Posting a telemetry message
* Getting a `RECEIVED INVALID MESSAGE` error in the logs

When I post a test telemetry message in a fresh ThingsBoard CE using Kafka as transport I get the following `RECEIVED INVALID MESSAGE` error in the rule engine logs:
```
2024-04-25 15:19:19,596 [tenant-dispatcher-1-16] WARN  o.t.server.actors.tenant.TenantActor - RECEIVED INVALID MESSAGE: QueueToRuleEngineMsg(super=TbRuleEngineActorMsg(msg=TbMsg(queueName=Main, id=ad76bae9-b84a-4ce1-b37a-4b9d564986f6, ts=1714058359593, type=POST_TELEMETRY_REQUEST, internalType=POST_TELEMETRY_REQUEST, originator=b3c03e80-02ed-11ef-a018-6130a3d89896, customerId=null, metaData=TbMsgMetaData(data={deviceType=TestType, deviceName=TestDevice, ts=1714049775775}), dataType=JSON, data={"temperature":25}, ruleChainId=10752b00-fa3c-11ee-9774-255d37be1f20, ruleNodeId=null, ctx=org.thingsboard.server.common.msg.TbMsgProcessingCtx@15bed06b, callback=org.thingsboard.server.service.queue.TbMsgPackCallback@50bc5cb8)), tenantId=103ed8c0-fa3c-11ee-9774-255d37be1f20, relationTypes=[], failureMessage=)
```

Using monolith, posting a telemetry test message works perfectly fine.

What could be the cause of this behaviour?

**Environment**

 * OS:  kubernetes
 * ThingsBoard: 3.6.3
 * Kafka 3.5.2

**Comment by sprijk** [comment]
Environment variables:
```yaml
env:
  - name: COAP_ENABLED
    value: "false"
  - name: HTTP_ENABLED
    value: "true"
  - name: LWM2M_ENABLED
    value: "false"
  - name: MQTT_ENABLED
    value: "true"
  - name: SNMP_ENABLED
    value: "false"
  - name: TB_SERVICE_ID
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: TB_SERVICE_TYPE
    value: "tb-rule-engine"
  - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
    value: "false
```
