### ISSUE TITLE
/data/db ownership to nobody nogroup

### ISSUE THREAD

**Issue by pg-goose** [thingsboard/thingsboard#11107]
**Describe the bug**
Thingsboard from tb-postgres 3.7.0 instance can not init the DB.
- [x] Try with v3.6.4

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard Version: `3.7.0`
  * Community
  * Ubuntu 22.04

**To Reproduce**
> Have docker installed in rootless mode

1. Create setup  
```
mkdir test
cd test
nano docker-compose.yml
```
_The docker compose file_  
```yml
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq
        - ./rabbitmq/logs:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s

 thingsboard:
    image: "thingsboard/tb-postgres"
    container_name: 'thingsboard'
    restart: unless-stopped
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: rabbitmq
      TB_QUEUE_RABBIT_MQ_USERNAME: guest
      TB_QUEUE_RABBIT_MQ_PASSWORD: guest
      TB_QUEUE_RABBIT_MQ_HOST: rabbitmq
      TB_QUEUE_RABBIT_MQ_PORT: 5672
    volumes:
      - ./thingsboard/data:/data
      - ./thingsboard/logs:/var/log/thingsboard
    depends_on:
      - rabbitmq
```
2. Create volumes  
```bash
mkdir -p ./thingsboard
# ls -la
# drwxrwxr-x  2 myuser docker  4096 jun 28 14:27 thingsboard

mkdir -p ./thingsboard/data && sudo chown -R 799:799 ./thingsboard/data
mkdir -p ./thingsboard/logs && sudo chown -R 799:799 ./thingsboard/logs
# ls -la
# drwxrwxr-x  2   799    799 4096 jun 28 14:29 data
# drwxrwxr-x  2   799    799 4096 jun 28 14:29 logs

docker compose -f docker-compose.yml up -d rabbitmq thingsboard
```

**Expected behavior**
Expected the thingsboard instance to start, a couple weeks ago I was spinning up instances no problem, last version seems to have broken something.

**Additional context**
Logs on the Thingsboard container
```
mkdir: cannot create directory ‘/data/db’: Permission denied
The files belonging to this database system will be owned by user "thingsboard".
initdb: error: could not create directory "/data/db": Permission denied
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

pg_ctl: database system initialization failed
creating directory /data/db ... Starting Postgresql...
pg_ctl: directory "/data/db" does not exist
Connecting to Postgres, 300 attempts left...
```

When attaching a terminal to the container and running `ls -la`
```bash
thingsboard@14421c05a104:/$ ls -la
···
drwxrwxr-x   2 nobody nogroup 4096 Jun 28 12:46 data
···
```
