### ISSUE TITLE
Health check in Docker-Compose

### ISSUE THREAD

**Issue by Godsgrav3** [thingsboard/thingsboard#11254]
**Component**

 * Generic

**Description**
I have a single docker-compose file that runs everything I need including Thingsboard-postgress and the associated Thingsboard IOT gateway. When I start up this docker-compose, I will get a lot of error/debug messages from the Thingsboard IOT gateway that the connection is refused. After a minute or 2, this will go away as the Thingsboard has completely started up.

I know in docker-compose, there is a section called "healthcheck" I tried to use that with the following option:
`healthcheck:
   test: ["CMD", "curl", "-f", "tcp://localhost:1883"]
   interval: 30s
   timeout: 10s`

and on the Thingsboard IOT gateway service I have the following:
`depends_on:
   thingsboard:
     condition: service_healthy`

This, however, doesn't work as curl is not available inside the docker image. So my question is, is there a way that I can use healthcheck in docker-compose to check if thingsboard-postgress has completely started up before I start up the IOT gateway?

**Environment**

 * OS:  Linux 24.04
 * Docker compose: version V2.28.1
 * ThingsBoard: version 3.6.4

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Godsgrav3** [comment]
For the moment I have implemented a crude solution which works, but ofcourse a real solution with health check would be best practice. If there is one in this docker container, or one will be build into it I would love to hear about it.

temporary solution:
On the service tb-gateway I have added the command field with the following commands: `sh -c "sleep 60s && /start-gateway.sh"`.

**Comment by pon0marev** [comment]
Try my approach with checking for open ports. This should be a good solution without installing additional tools.
```
  thingsboard:
    restart: always
    image: "thingsboard/tb-pe:3.7.0PE"
    ports:
      - "8080:8080"
      - "1883:1883"
    healthcheck:
      # Check that entries for ports 1883 and 8080 exist in the /proc/net/tcp file. Port 1883 is represented as :075B and port 8080 is represented as :1F90.
      test: ["CMD-SHELL", "grep ':075B' /proc/net/tcp && grep ':1F90' /proc/net/tcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
```
