### ISSUE TITLE
Error - User with email 'sysadmin@thingsboard.org' already present in database!

### ISSUE THREAD

**Issue by andyabcd1** [thingsboard/thingsboard#11694]
**Environment**
Installation: Docker-compose
Database: Postgresql database hosted in GCP

```
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ...
    environment:
      - TB_QUEUE_TYPE=in-memory
      - SPRING_DATASOURCE_URL=xxx
      - SPRING_DATASOURCE_USERNAME=xxx
      - SPRING_DATASOURCE_PASSWORD=xxx
```

**Reproduce Step**
1. Start the docker container with External Database Setup in docker-compose by running `docker-compose up -d`
2. Run `docker-compose down`
3. Restart the container by running `docker-compose up -d`
4. Run `docker ps` & then `docker logs -f <container_id>`
5. Error shows as below

```
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org' already present in database!
``` 
**What I tried**
I tried to run `docker exec -it <container_id> sh` and create empty .firstLaunch file in /usr/share/thingsboard/data directory in the container, then restart it, but still hitting the same error, according to [this solution](https://stackoverflow.com/a/71016851/24899983)

I know I can delete the corresponding user database table in my external database, but it doesn't make sense to recreate one whenever I restart the docker container. Any workaround for it, especially in a Production environment?
