### ISSUE TITLE
Upgrade to PE with Cassandra DB

### ISSUE THREAD

**Issue by SamuelHelbling** [thingsboard/thingsboard#11957]
**Component**

 * Installation

**Description**
I am currently running the Community Edition of Thingsboard, but have now upgraded to the Professional Edition. My current CE installation runs on the thingsboard/tb-cassandra:3.8.1 docker image.  How do I set up a Thingsboard PE with Docker and Cassandra DB and migrate my data? I have not found any information on this in the installation instructions: https://thingsboard.io/docs/user-guide/install/pe/docker/?ubuntuThingsboardQueue=inmemory.

This is what my current Docker-Compose file looks like:

```yml
version: '3.0'
services:
  thingsboard:
    restart: always
    image: "thingsboard/tb-cassandra:3.8.1"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
```

Thank you

**Environment**

 * OS:  Ubuntu 20.04.6 LTS
 * ThingsBoard: CE 3.8.1 currently, PE 3.8.1 is the goal
