### ISSUE TITLE
Configuration for the launching of ThingsBoard JS Executor as a containerised service.

### ISSUE THREAD

**Issue by AVTaran** [thingsboard/thingsboard#12067]
**Component**

 * Installation

**Description**
Hello all.
Sorry if there are some related discussions about it that I didn't find.

We are currently on the ThingsBoard 3.6.4PE version. Not dockerised, monolithic. ThingsBoard, PostgreSQL and Kafka runs on a single machine (20.04 Ubuntu, AWS).
And would like to upgrade to 3.7.0PE
But we hit the issue during the update: "Regular expression running for too many iterations. The operation could NOT be gracefully interrupted."
https://github.com/thingsboard/thingsboard/issues/11077

We tried to launch the JS executor in a separate container.
docker-compose.yml:
```
services:
  tb-js-executor:
    restart: always
    image: thingsboard/tb-pe-js-executor:3.7.0PE
    container_name: tb-js-executor
    environment:
      REMOTE_JS_EVAL_REQUEST_TOPIC: js_eval.requests
      LOGGER_LEVEL: "info"
      LOG_FOLDER: "logs"
      LOGGER_FILENAME: "tb-js-executor-%DATE%.log"
      DOCKER_MODE: "true"
      SCRIPT_BODY_TRACE_FREQUENCY: "1000"
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: localhost:9092
    network_mode: "host"
```
It works, but we are having an issue with the increasing number of containers:

The container exposes the 8888 port for the `livenessProbe` checks.
And if we try to scale it up (`scale: 5` in the docker-compose.yml).
It will start the first container's instance but not the others, because the exposed port(8888) will be occupied.
What options do we have to increase the number of containers? 

**Environment**

 * OS:  20.04 Ubuntu
 * ThingsBoard: 3.7.0PE / 3.6.4PE 
 * ThingsBoard JS Executor: 3.7.0PE / 3.6.4PE
