### ISSUE TITLE
What does RW logging level mean for Dashboard Audit 

### ISSUE THREAD

**Issue by txf-** [thingsboard/thingsboard#12231]
**Audit Logs**

 * Audit Logs

**Description**
I enabled the RW level for the following types in the thingsboard.yml file:

```
"dashboard": "${AUDIT_LOG_MASK_DASHBOARD:RW}" # Dashboard logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
"widget_type": "${AUDIT_LOG_MASK_WIDGET_TYPE:RW}" # Widget type logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
"widgets_bundle": "${AUDIT_LOG_MASK_WIDGETS_BUNDLE:RW}" # Widget bundles logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
```

However, from what I can tell, when I open a dashboard that should count as a read? Nothing is registered in the audit log. Is there any documentation pertaining to the mechanics of what a read or a write means for each of the audit types?

There are others that such as reading the rule_chain, which also do not register any event in the audit log.

**Environment**

 * OS: Raspberry Pi OS Bookworm
 * ThingsBoard: 3.8.1
 * Browser: Chrome 121

Here is the complete section in the thingsboard.yml:

```
#Audit log parameters
audit-log:
  # Enable/disable audit log functionality.
  enabled: "${AUDIT_LOG_ENABLED:true}"
  # Logging levels per each entity type.
  # Allowed values: OFF (disable), W (log write operations), RW (log read and write operations)
  logging-level:
    mask:
      "device": "${AUDIT_LOG_MASK_DEVICE:RW}" # Device logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "asset": "${AUDIT_LOG_MASK_ASSET:RW}" # Asset logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "dashboard": "${AUDIT_LOG_MASK_DASHBOARD:RW}" # Dashboard logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "widget_type": "${AUDIT_LOG_MASK_WIDGET_TYPE:RW}" # Widget type logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "widgets_bundle": "${AUDIT_LOG_MASK_WIDGETS_BUNDLE:RW}" # Widget bundles logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "customer": "${AUDIT_LOG_MASK_CUSTOMER:RW}" # Customer logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "user": "${AUDIT_LOG_MASK_USER:RW}" # User logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "rule_chain": "${AUDIT_LOG_MASK_RULE_CHAIN:RW}" # Rule chain logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "alarm": "${AUDIT_LOG_MASK_ALARM:RW}" # Alarm logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "entity_view": "${AUDIT_LOG_MASK_ENTITY_VIEW:RW}" # Entity view logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "device_profile": "${AUDIT_LOG_MASK_DEVICE_PROFILE:RW}" # Device profile logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "asset_profile": "${AUDIT_LOG_MASK_ASSET_PROFILE:RW}" # Asset profile logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "edge": "${AUDIT_LOG_MASK_EDGE:RW}" # Edge logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "tb_resource": "${AUDIT_LOG_MASK_RESOURCE:RW}" # TB resource logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
      "ota_package": "${AUDIT_LOG_MASK_OTA_PACKAGE:RW}" # Ota package logging levels. Allowed values: OFF (disable), W (log write operations), RW (log read and write operation
```
