### ISSUE TITLE
Widget Editor Unable to Connect when Saving after Previously Working

### ISSUE THREAD

**Issue by phishstang65** [thingsboard/thingsboard#12979]
I bought Thingsboard Professional and installed it on a 4 processor / 8 GB RAM digital ocean droplet.

I installed with docker-compose and am running version 3.9.1PE (docker-compose.yml) below. 

Yesterday, after installing, I created a custom widget and dashboard and succesfully saved the widget. Today, I went to work on the widget again and cannot save any changes. The save button causes the 'saving' progress indicator to move for around 60 seconds and then finally display an error message "Unable to connect". I have googled and used claude to help troubleshoot, however nothing seems to resolve it. I thought it was some sort of resource issue but I have plenty of RAM and expanded the pool size. I have reboot the VM and restartd docker-compose many times.

![Image](https://github.com/user-attachments/assets/6bc2d105-aa36-4caa-a3f1-875f15997c52)

How can I fix this? It worked yesterday but now doesn't. Thank you.

Memory:
```
root@bd-poc-kin:~/thingsboard# free -mt
               total        used        free      shared  buff/cache   available
Mem:            7940        2711        3908          55        1620        5229
Swap:              0           0           0
Total:          7940        2711        3908
```

Load:
`top - 15:07:09 up 25 min,  3 users,  load average: 0.54, 1.98, 2.11`

Docker-Compose:
```
services:
  mytbpe:
    restart: always
    image: "thingsboard/tb-pe:3.9.1PE"
    container_name: thingsboard-mytbpe
    ports:
      - "8080:8080"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TB_LICENSE_SECRET: redacted
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_BY_DEFAULT_NULL_ORDERING: none
      SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 100
      TB_DATABASE_TS_CONNECTION_TIMEOUT: 60000
      TB_DATABASE_CONNECTION_TIMEOUT: 60000
    volumes:
      - ./mytbpe-data:/data
      - ./mytbpe-logs:/var/log/thingsboard
  postgres:
    restart: always
    image: "postgres:15"
    container_name: thingsboard-postgres
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: "--max-connections=200"
    volumes:
      - ./mytbpe-data/db:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=200"]
```
