### ISSUE TITLE
[Gateway] Timeseries not saved to Latest Telemetry—only attributes are stored

### ISSUE THREAD

**Issue by Benziza** [thingsboard/thingsboard#13357]
# Bug Report: Timeseries not saved to Latest Telemetry—only attributes are stored

## Describe the bug  
When publishing MQTT messages through ThingsBoard IoT Gateway with dynamic device provisioning enabled, the gateway auto-creates the target device and parses the JSON correctly—but all numeric fields defined under **timeseries** (e.g. `temperature`) end up in the device’s **Client attributes**. Nothing ever appears in **Latest Telemetry**, despite logs showing `TelemetryEntry` values.

---

## Your Server Environment  
- **Own setup**  
  - Deployment: monolith  
  - Deployment type: docker-compose  
  - ThingsBoard Version: 3.7-stable (`thingsboard/tb-postgres:3.7-stable`)  
  - Edition: Community  
  - OS Name and Version: Ubuntu 22.04 LTS  

### Gateway & Broker Containers  
| Container      | Image                                | Port Mapping  |
|----------------|--------------------------------------|---------------|
| `mqtt-broker`  | `eclipse-mosquitto:2.0`              | `1884:1883`   |
| `tb-gateway`   | `thingsboard/tb-gateway:3.7-stable`  | `5000:5000`   |

---

## Your Client Environment  
**Desktop**  
- OS: Windows 11  
- Browser: Microsoft Edge  
- Version: 136.0.3240.64 (64-bit)

---

## Your Device  
- Connectivity: Gateway (MQTT)  
- ThingsBoard IoT Gateway version: 3.7-stable (`thingsboard/tb-gateway:3.7-stable`)  
- MQTT broker: Mosquitto (`eclipse-mosquitto:2.0`)

---

## To Reproduce  
1. **docker-compose.yml**:
   ```yaml
   services:
     mqtt-broker:
       image: eclipse-mosquitto:2.0
       container_name: mqtt-broker
       ports:
         - "1884:1883"
     tb-gateway:
       image: thingsboard/tb-gateway:3.7-stable
       container_name: tb-gateway
       ports:
         - "5000:5000"
       environment:
         - host=host.docker.internal
         - port=1884
         - accessToken=<GATEWAY_TOKEN>
       depends_on:
         - mqtt-broker
   ```  
2. In ThingsBoard **Gateways → Your Gateway → Configuration → MQTT Connector → Data mapping**, use:
   ```json
   {
      "topicFilter": "rfid/temp",
      "subscriptionQos": 0,
      "converter": {
        "type": "json",
        "deviceInfo": {
          "deviceNameExpression": "TestTemp",
          "deviceNameExpressionSource": "message",
          "deviceProfileExpressionSource": "message",
          "deviceProfileExpression": "default"
        },
        "attributes": [
          {
            "key": "timestamp",
            "type": "string",
            "value": "${timestamp}"
          }
        ],
        "timeseries": [
          {
            "key": "temperature",
            "type": "double",
            "value": "${temperature}",
            "reportStrategy": {
              "type": "ON_RECEIVED"
            }
          }
        ]
      }
    },
   ```  
3. Publish a test message:
   ```bash
   mosquitto_pub -h localhost -p 1884 -t rfid/temp -m '{"rfid":"enter","temperature":55,"timestamp":"2025-05-10T18:10:00Z"}'
   ```  
4. Check ThingsBoard UI under **Devices → Temp_1**:
   - **Client attributes** shows `timestamp: 2025-05-10T18:10:00Z`  
   - **Latest Telemetry** is empty

---

## Expected behavior  
Fields defined under **timeseries** (`temperature`) should be stored as telemetry entries and visible in the **Latest Telemetry** tab of the auto-provisioned device.
________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.
