### ISSUE TITLE
MQTT / X.509 authentication broken

### ISSUE THREAD

**Issue by echodelt** [thingsboard/thingsboard#1355]
Hi,

The MQTT / X.509 device authentication feature seems to be broken since the release of the Thingsboard 2.2.0 version.

I could previously use it with TB 2.0 and TB 2.1.3, pushing data with a mosquitto client.

Now with the same server MQTT / SSL configuration and the same server and device certificates, I get this error message in the log file : 

`[nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [localhost:41928] Invalid message received`

(no more details available in the log file)

Here are my server settings :

```
  # Local MQTT transport parameters
  mqtt:
    enabled: "${MQTT_ENABLED:true}"
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    bind_port: "${MQTT_BIND_PORT:8883}"
    timeout: "${MQTT_TIMEOUT:10000}"
    netty:
      leak_detector_level: "${NETTY_LEAK_DETECTOR_LVL:DISABLED}"
      boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
      worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
      max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"

  ssl:
    enabled: "${MQTT_SSL_ENABLED:true}"
    protocol: "${MQTT_SSL_PROTOCOL:TLSv1.2}"
    key_store: "${MQTT_SSL_KEY_STORE:mqtt_server.tb1.jks}"
    key_store_password: "${MQTT_SSL_KEY_STORE_PASSWORD:my_password}"
    key_password: "${MQTT_SSL_KEY_PASSWORD:my_password}"
    key_store_type: "${MQTT_SSL_KEY_STORE_TYPE:JKS}"
```
And data is pushed with :

`mosquitto_pub -h "tb1" -p 8883  --tls-version tlsv1.2 -t "v1/devices/me/telemetry" --cafile mqtt_server.tb1.pub.pem --key mqttclient.key --cert mqttclient.pem -m '{"temperature":12.3, "humidity":45.6}' `

Has anyone else encountered a problem with X.509 authentication using TB 2.2 ?

Greetings,

Thanks
