### ISSUE TITLE
can't upgrade from 3.8.1 to 3.9.0 PE

### ISSUE THREAD

**Issue by owen63** [thingsboard/thingsboard#13582]
**Describe the bug**
**can't upgrade from 3.8.1 to 3.9.0 PE**

**Your Server Environment**

* own setup
  * Deployment: microservices
  * Deployment type: docker-compose
  * ThingsBoard Version: professional

**To Reproduce**
I started an upgrade from 3.8.1 to 3.9.0. I also changed from monolithic to microservices.
Following this upgrade guide: https://thingsboard.io/docs/user-guide/install/pe/docker/

**Expected behavior**
Upgrade success

**Screenshots**
 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.9.0PE)
 ===================================================

Unexpected error during ThingsBoard installation!
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ALTER TABLE tb_schema_settings ADD COLUMN IF NOT EXISTS product varchar(2) DEFAULT 'CE']
...
Caused by: org.postgresql.util.PSQLException: ERROR: relation "tb_schema_settings" does not exist

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @owen63,

After a quick review, I assume that you ran the upgrade from the PE using the CE image. But to confirm the root cause, the following information is required:

 - The full installation log.
 - Steps to reproduce this issue (list of commands that you used), so I can try to test it on my local machine.
 - Docker Compose file that you used.

**Comment by owen63** [comment]
[install.log](https://github.com/user-attachments/files/20764396/install.log)

- docker pull thingsboard/tb-pe-node:3.9.0PE
- docker compose stop thingsboard-pe
- docker compose run --rm -e UPGRADE_TB=true thingsboard-pe

[docker-compose.yml](https://github.com/user-attachments/files/20764509/docker-compose.yml.txt)

**Comment by sumin-denys** [comment]
@owen63,

To help us diagnose this issue, could you please connect to your PostgreSQL database and check for the "tb_schema_settings" table?

Please execute the following commands in your PostgreSQL client (e.g., psql) and provide the output:

1. Connect to your PostgreSQL database:

```bash
psql -h your_host -p your_port -d your_database -U your_user
```
[[REMARK: You need to replace your_host, your_port, your_database, and your_user with the actual connection details for the  database.]]

After connecting, list all tables to check for `tb_schema_settings` and its casing:

```sql
\dtS
```
Then check what inside this `tb_schema_settings`:

```sql
SELECT * FROM tb_schema_settings;
```

This information will help me determine if the table exists and what can be root cause of issue.

**Comment by owen63** [comment]
thingsboard-# \dt tb_schema*
               List of relations
 Schema |        Name        | Type  |  Owner   
--------+--------------------+-------+----------
 public | tb_schema_settings | table | postgres
(1 row)

thingsboard-# SELECT * FROM tb_schema_settings
thingsboard-#

**Comment by owen63** [comment]
Note that my upgrade was from 3.8.1 monolithic to 3.9.0 node. Perhaps I should not have switched?

**Comment by sumin-denys** [comment]
Hi @owen63,

I am not sure that this issue is related to the monolithic or node deployment, but I will be glad to double-check it. 

Could you please provide an example of your previous monolithic `docker-compose.yml` so I can reproduce the same condition for testing?

Additionally, could you please advise if you have previously transitioned from CE to PE?

Also, I don't see the content of `tb_schema_settings` in this [comment](https://github.com/thingsboard/thingsboard/issues/13582#issuecomment-2985826890)
Could you please add `;` to the `SELECT * FROM tb_schema_settings` and run it again? The example of a correct command:
```sql
SELECT * FROM tb_schema_settings;
```

**Comment by owen63** [comment]
docker-compose for ThingsBoard 3.8.1:
```
  tb-monolith:
    restart: always
    image: "thingsboard/tb-pe:3.8.1PE"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "8883:8883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      TB_LICENSE_SECRET: ********************
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      MQTT_SSL_ENABLED: true
      MQTT_SSL_CREDENTIALS_TYPE: PEM
      MQTT_SSL_PEM_CERT: /config/server.pem
      MQTT_SSL_PEM_KEY: /config/server_key.pem
    volumes:
      - ~/.mytbpe-data:/data
      - ~/.mytbpe-logs:/var/log/thingsboard
      - ~/thingsboard:/config

  postgres:
    restart: always
    image: "postgres:15"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: ********
    volumes:
      - ~/.mytbpe-data/db:/var/lib/postgresql/data
```
I have not previously transitioned from CE to PE

```
thingsboard=# SELECT * FROM tb_schema_settings;
 schema_version | product 
----------------+---------
        3006004 | PE
(1 row)
```
