### ISSUE TITLE
Can I interface IoT-Gateway with TB Edge?

### ISSUE THREAD

**Issue by jpiwek** [thingsboard/thingsboard#13597]
Component
    Generic

Description
Hi,

currently I run a TB Server (native instance) and IoT-Gateway (with Docker) on my RPi5 which works very well. 
I want to interface 2-5 Modbus, proprietary protocol devices.
I just noticed that TB Edge is a more lightweight solution for my RPi5 device comparing to TB Server.
Can I interface TB Edge with IoT-Gateway locally on the same RPi5?
Then I would host the TB Server instance on my PC rather then on Rpi5..

Environment

    OS: Raspi Bookworm with Linux 6.6.62+rpt-rpi-2712
    ThingsBoard: 4.0.1
    IoT-Gateway: 3.7.5
    Browser: Firefox

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
Please get familiar with the following documentation:
https://thingsboard.io/docs/edge/config/deploying-edge-alongside-iot-gateway/

**Comment by jpiwek** [comment]
OK thanks. Just followed the instruction:

This is my setup. all instances running on the same PI:
-TB Server (native instance)-> TB Edge (Docker)-> TB IoT-Gateway (Docker)
As far as I see Progress DB is shared by TB Server and TB Edge in my setup.

Do I need to update the IoT-Gateway port 1883 to 11883 so that data is send to TB-Edge?
Seems like it's working that way, when TB Edge works as proxy for IoT-Gateway. Let me know your feedback on this and anything else I have to consider.


**TB-Edge:**
```
version: '3.8'
services:
  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:4.0.1EDGE"
    ports:
      - "18080:8080"
      - "11883:1883"
      - "15683-15688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: fd090c0b-bee3-45c4-9ff3-65a4f85cb767
      CLOUD_ROUTING_SECRET: 61nq1k7mdc97ywcto8ah
      CLOUD_RPC_HOST: pi5-dev
      CLOUD_RPC_PORT: 7070
      CLOUD_RPC_SSL_ENABLED: false
    volumes:
      - tb-edge-data:/data
      - tb-edge-logs:/var/log/tb-edge

  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-edge-postgres-data:/var/lib/postgresql/data

volumes:
  tb-edge-data:
    name: tb-edge-data
  tb-edge-logs:
    name: tb-edge-logs
  tb-edge-postgres-data:
    name: tb-edge-postgres-data

```


**TB IoT-Gateway**
```
version: '3.4'
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway:3.7-latest
    container_name: tb-gateway
    restart: always

    # Ports bindings - required by some connectors
    ports:
        - "5000:5000" # Comment if you don't use REST connector and change if you use another port
        # Uncomment and modify the following ports based on connector usage:
#        - "1052:1052" # BACnet connector
#        - "5026:5026" # Modbus TCP connector (Modbus Slave)
#        - "50000:50000/tcp" # Socket connector with type TCP
#        - "50000:50000/udp" # Socket connector with type UDP

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - host=pi5-dev
      - port=11883
      - accessToken=test

    # Volumes bind
    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions

```
