### ISSUE TITLE
How to install two TB instances in a docker container

### ISSUE THREAD

**Issue by owen63** [thingsboard/thingsboard#13639]
**Component**

 * Installation

**Description**
I have a production TB instance installed in a docker container. I want to add another TB instance - for development. I have attached a docker compose file that I think is required but I would appreciate a review in case I've missed anything. It shows the existing productoin instance and the proposed dev instance. Also I note
that there is a `tb-pe-docker-compose` directory on the host. I don't know if it is needed after installation and/or will it be overwritten when I install the new instance and affect the existing instance?

[docker-compose-two-tb.yml.txt](https://github.com/user-attachments/files/20895610/docker-compose-two-tb.yml.txt)

**Comment by sumin-denys** [comment]
Hi @owen63,

As I can see from the configuration that you provided, the `tb-pe-docker-compose` is not used in your deployment, so it is not needed. It shouldn't affect the existing instance, and it shouldn't be overwritten.

Also, before deploying the second instance, it is essential to verify that you use different keys, as License Server Architecture dictates that each ThingsBoard client sends a License check request. If the license key is bound with more than one InstanceID, ThingsBoard will shut down the instances.

I should notice that it isn't required to have two different PostgreSQL databases for each ThingsBoard instance. You can create, for example, `thingsboard-development-db` for your development instance and configure the connection for the development instance to this database.

In brief, the whole configuration looks good to me.

**Comment by owen63** [comment]
Can you elaborate on the configuration for two ThingsBoard databases within the one Postgres container. It seems that only one can be defined via the Postgres docker config:
```
postgres:
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
```
And how does this relate to the ThingsBoard container config:
```
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
```

**Comment by owen63** [comment]
Do I use `POSTGRES_MULTIPLE_DATABASES` and match those names in each `SPRING_DATASOURCE_URL`? e.g. 

```
thingsboard-prod:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard

thingsboard-dev:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-dev-db

postgres:
    environment:
      POSTGRES_MULTIPLE_DATABASES: thingsboard,tb-dev-db
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD: postgres
```
