### ISSUE TITLE
Tuning Hikari connection pool for PostgreSQL 

### ISSUE THREAD

**Issue by JohnBat26** [thingsboard/thingsboard#1888]
Hi.
Recently we have met troubles with tuning maximumPoolSize for TB in docker installation.
Why connection pool settings do not  put in thingsboard settings ? 
Default maxSize is 10 and this amount is very small, isn't it ?

**Comment by ban2derlog** [comment]
Hi, for this you need to add Configuration parameter for ThingsBoard in docker-compose.yml like this:
```
services:
  mytbpe:
    restart: always
    image: "thingsboard/tb-pe:3.3.4.1PE"
    ports:
      .....
    environment:
      SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: X
```
where X - is maximum quantity of connection at time.
At latest version default value is 16, but you can rise it to 25, for example.

Also you can check all parameters for ThingsBoard here:
https://thingsboard.io/docs/pe/user-guide/install/config/#sql-dao-configuration
