### ISSUE TITLE
Spring MVC CORS Mapping in a Microservices Setup

### ISSUE THREAD

**Issue by mon-dragon** [thingsboard/thingsboard#1897]
Does anybody know how I can define this configuration from thingsboard.yml in a microservices env file?

```yml
spring.mvc.cors:
   mappings:
      "[/api/**]":
         allowed-origins: "*"
         allowed-methods: "*"
         allowed-headers: "*"
         max-age: "1800"
         allow-credentials: "true"
```
