### ISSUE TITLE
Thingsboard installation issue with docker

### ISSUE THREAD

**Issue by bodiroga** [thingsboard/thingsboard#2238]
Hi thingsboard team!

I'm trying the latest thingsboard docker package (tb-cassandra:latest) on a Intel NUC (with i3 and 8Gb of RAM, Ubuntu server 18.04), but it doesn't start correctly. This is the docker-compose file I'm using:

```
version: '3.6'

services:
  thingsboard:
    container_name: thingsboard
    image: thingsboard/tb-cassandra:latest
    restart: always
    ports:
      - 9090:9090
      - 1883:1883
      - 5683:5683
    volumes:
      - /opt/docker/thingsboard/data:/data
      - /opt/docker/thingsboard/logs:/var/log/thingsboard
```

And here you can find the relevant log files ('thingsboard.log' and 'gc.log.0.current'): [thingsboard-logs.zip](https://github.com/thingsboard/thingsboard/files/3926033/thingsboard-logs.zip)

I'm able to reproduce the error on my development laptop (5 years old i5 and Ubuntu 16.04), so I'm not sure what could be the problem. The installation is completely clean in both cases, 'data' and 'logs' folders are empty before launching the docker-compose command.

Am I the only one seeing this problem? :cry: 

Many thanks for your help and if you need more information, don't hesitate to ask.

Best regards,

Aitor

**Comment by vvlladd28** [comment]
Hi,
Please use the instruction https://thingsboard.io/docs/user-guide/install/docker/  and use CLI command to create Docker container. I test to 18.04 docker image it work

**Comment by datenheim** [comment]
Dont know what there is going wrong, but maybe defining the network can help?
Here my compose-file running via portainer on ZBOX nano quite fine:
```
version: "2"
services:
  thingsboard:
    container_name: iot_thingsboard
    image: thingsboard/tb-cassandra:2.4.1
    environment:
      - VIRTUAL_HOST=iot.xxx.de
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=iot.xxx.de
      - LETSENCRYPT_EMAIL=x@xxx.de
      - SSL_ENABLED=false
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /xdd/thingsboard/data:/data
      - /xdd/thingsboard/logs:/var/log/thingsboard
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9090:9090
      - 5683:5683
      - 1883:1883
    networks:
      - default

networks:
  default:
    external:
      name: proxyng_apps
```
The difference is the timezone is taken from host and network is connected to nginx-proxy-companion to add letsencrypt. If you dont need that you can omit the virtualhost and letsencrypt environment line.
While not working from portainer updating this stack requires 3 steps:

1. stop the stack either from portainer or with `docker-compose down`
2. pull the new image ` docker pull thingsboard/tb-cassandra:2.4.1`
3. upgrade per command line `docker run -it --volumes-from iot_thingsboard --rm thingsboard/tb-cassandra:2.4.1 upgrade-tb.sh `
4. update the portainer stack or compose file to have the right version number, again either via portainer or with nano and `docker-compose up -d`

Of course this can also be done with :latest instead of a specific number but I prefer to have total control. Portainer might pull the latest image but not execute the upgrade-tb.sh when it start the stack so that can cause trouble. If you work wit docker-compose directly it should be save.

Think its not an "issue" but a topic for a discussion forum ;-)
