### ISSUE TITLE
Trouble with gateway

### ISSUE THREAD

**Issue by Stude12** [thingsboard/thingsboard#2251]
Hello everybody,

I try to use the iot-gateway. I have a fresh install of thingsboard-2.4.1 and tb-gateway-1.4.0. My system is `Linux smarthome-EasyNote-TJ65 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Mate GUI)`
So I launch a MQTT broker -> mosquitto version 1.4.15  on port 1882 trough the following command : `sudo mosquitto -p 1882`
In the ThingsBoard Tenant UI, I create a Device with the Gateway type and the credential is "ibj3x4TVgrI7yB2HR6hR". I try to parameter a MQTT Extension, I have this mqtt-config.json 
```
{
  "brokers": [
    {
      "host": "localhost",
      "port": 1882,
      "ssl": false,
      "retryInterval": 3000,
      "credentials": {
        "type": "anonymous"
      },
      "mapping": [
        {
          "topicFilter": "sensors",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameJsonExpression": "${$.serialNumber}",
            "attributes": [
            ],
            "timeseries": [
              {
                "type": "double",
                "key": "temperature",
                "value": "${$.temperature}"
              }
            ]
          }
        },
        {
          "topicFilter": "sensor/+/temperature",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/temperature)",
            "timeout": 60000,
            "timeseries": [
              {
                "type": "double",
                "key": "temperature",
                "value": "${$.value}"
              }
            ]
          }
        }
      ],
      "connectRequests": [
        {
          "topicFilter": "sensors/connect",
          "deviceNameJsonExpression": "${$.serialNumber}"
        },
        {
          "topicFilter": "sensor/+/connect",
          "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/connect)"
        }
      ],
      "disconnectRequests": [
        {
          "topicFilter": "sensors/disconnect",
          "deviceNameJsonExpression": "${$.serialNumber}"
        },
        {
          "topicFilter": "sensor/+/disconnect",
          "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/disconnect)"
        }
      ],
      "attributeRequests": [
        {
          "topicFilter": "sensors/attributes",
          "deviceNameJsonExpression": "${$.serialNumber}",
          "attributeKeyJsonExpression": "${$.key}",
          "requestIdJsonExpression": "${$.requestId}",
          "clientScope": false,
          "responseTopicExpression": "sensors/${deviceName}/attributes/${responseId}",
          "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
        },
        {
          "topicFilter": "sensors/+/attributes/+/request/+",
          "deviceNameTopicExpression": "(?<=sensors\/)(.*?)(?=\/attributes)",
          "attributeKeyTopicExpression": "(?<=attributes\/)(.*?)(?=\/request)",
          "requestIdTopicExpression": "(?<=request\/)(.*?)($)",
          "clientScope": false,
          "responseTopicExpression": "sensors/${deviceName}/attributes/${attributeKey}/response/${requestId}",
          "valueExpression": "${attributeValue}"
        }
      ],
      "attributeUpdates": [
        {
          "deviceNameFilter": ".*",
          "attributeFilter": ".*",
          "topicExpression": "sensor/${deviceName}/${attributeKey}",
          "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
        }
      ],
      "serverSideRpc": [
        {
          "deviceNameFilter": ".*",
          "methodFilter": "echo",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
          "responseTimeout": 10000,
          "valueExpression": "${params}"
        },
        {
          "deviceNameFilter": ".*",
          "methodFilter": "no-reply",
          "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
          "valueExpression": "${params}"
        }
      ]
    }
  ]
}
```
and this tb-gateway.yml 
```
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "localhost"
        port: 1883
        retryInterval: 4000
        maxInFlight: 1000
        security:
          accessToken: "ibj3x4TVgrI7yB2HR6hR"
      remoteConfiguration: true
      extensions:
        -
          id: "mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config.json

```

In the gateway device on the thingsboard UI, I have configured the extension with the same as mqtt-config.json -> broker localhost, port 1882, Mapping : Json, topic filter : sensors, deviceNameExpression : ${$.serialNumber}, Timeseries : Key : temperature, Type : Double, Value : ${$.temperature}. The status is Sync.

So I push a message via :  ```mosquitto_pub -h localhost -p 1882 -t "sensors" -m '{"serialNumber": "toto","temperature":42.0}'```

But I have NullPointerException in the tb-gateway logs .
```
2019-12-09 10:57:15,017 [MQTT Call: 71a5f348-b926-4b6e-9520-47700fd14eb1] INFO  o.t.g.e.m.c.l.MqttTelemetryMessageListener - [sensors] Failed to decode message: [123, 34, 115, 101, 114, 105, 97, 108, 78, 117, 109, 98, 101, 114, 34, 58, 32, 34, 116, 111, 116, 111, 34, 44, 34, 116, 101, 109, 112, 101, 114, 97, 116, 117, 114, 101, 34, 58, 52, 50, 46, 48, 125]
java.lang.NullPointerException: null
	at org.thingsboard.gateway.extensions.mqtt.client.conf.mapping.MqttJsonConverter.convert(MqttJsonConverter.java:58)
	at org.thingsboard.gateway.extensions.mqtt.client.listener.MqttTelemetryMessageListener.messageArrived(MqttTelemetryMessageListener.java:42)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:491)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I don't understand why... 
Can someone help me ?
