### ISSUE TITLE
How can I connect to PostgreSQL in thingsboard docker conainer from remote host?

### ISSUE THREAD

**Issue by CaiBaoHong** [thingsboard/thingsboard#2285]
**I have try following this steps but fail:**

pull thingsboard image:

```bash
docker pull thingsboard/tb-postgres
```

run image, and map the postgresql port `5432`:

```bash
docker run -it -p 5432:5432 -p 9090:9090 -p 2883:1883 -p 5683:5683/udp -v ~/thingsboard/data:/data -v ~/thingsboard/logs:/var/logs/thingsboard --name thingsboard --restart always thingsboard/tb-postgres
```

enter docker container and try to change settings for enabling access from host machine or remote host:

```bash
docker exec -it thingsboard bash
```

(in container) query where is the postgresql data directory now:

```bash
root@65706b0eee29:~# su - postgres
postgres@65706b0eee29:~$ psql
psql (9.6.13)
Type "help" for help.

postgres=# show data_directory;
 data_directory 
----------------
 /data/db
(1 row)
```

(in container) set a password for db user `postgres` :

```
postgres=# \password postgres
Enter new password: 
Enter it again: 
postgres=# \q
```

(in container) install tools and set env vars:

```bash
root@65706b0eee29:~# apt-get update && apt-get install -y net-tools vim
root@65706b0eee29:~# su - postgres
postgres@65706b0eee29:~$ vim .bash_profile

----------------------------------------------
export PGDATA=/data/db
export PATH=/usr/lib/postgresql/9.6/bin:$PATH
----------------------------------------------
```

(in container) modify config file, try to enable remote access:

```bash
cd /etc/postgresql/9.6/main

vim postgresql.conf
-----------------------------------------------------
(1) change: listen_address='localhost' --> listen_address='*'
(2) uncommit: password_encrytion=on
-----------------------------------------------------

vim pg_hba.conf
-----------------------------------------------------
(1) add two line:
host    all    all    0.0.0.0/0    md5
host    all    all    ::/0         md5
-----------------------------------------------------
```

(in container) restart postgresql in container

```
postgres@65706b0eee29:~$ pg_ctl status # <-- view status
pg_ctl: server is running (PID: 1175)
/usr/lib/postgresql/9.6/bin/postgres
postgres@65706b0eee29:~$ pg_ctl stop  # <-- stop
waiting for server to shut down.... done
server stopped
postgres@65706b0eee29:~$ pg_ctl start # <-- start
server starting
postgres@65706b0eee29:~$ LOG:  could not bind IPv6 socket: Cannot assign requested address
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  database system was shut down at 2019-12-23 07:49:05 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
```

`ctrl+p+q` to leave container and keep container running, then i try to connect the postgresql in the container:

```bash
caibh@home:~$ psql -U postgres -d postgres -h 127.0.0.1 -p 5432
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Please help, thinks!**

**Comment by digitib** [comment]
Hi, I think you must first stop thingsboard service before trying to connect.

**Comment by arjun289** [comment]
@CaiBaoHong did you manage to connect?

**Comment by Nathan-ma** [comment]
Please my friend, let us know if you were actually able to do it!

**Comment by CaiBaoHong** [comment]
> Please my friend, let us know if you were actually able to do it!

I have not figure it out. But I try another way: 
0. install postgresql on my linux machine
1. clone the source code on my linux develop machine
2. `mvn install -DskipTests=true`
3.  invoke the shell script `install_dev_db.sh` in `thingsboard/application/target/bin/install`
4. config the postgresql password in `thingsboard/application/src/main/resources/thingsboard.yml`
5. start the application

**Comment by Nathan-ma** [comment]
@CaiBaoHong 

So, I have figured this out!
there are two ways you can achieve this. The most robust way is having Postgres as another container.

Docker-composer.yml file would look like this:
```
version: '2.2'
services:
  thingsboard:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    expose:
      - "80"
    ports:
      - "80:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
    volumes:
      - /home/ubuntu/docker/.thingsboard-data:/data
      - /home/ubuntu/docker/.thingsboard-logs:/var/log/thingsboard
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    image: "postgres:12"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/ubuntu/docker/.thingsboard-data/db
```
The code above expects you to create two folders, the .thingsboard-data, and the .thingsboard-log. these will be your volumes on Postgres.

The other way would be creating an external network on docker, instead of the default. take a look at docker documentation, because I don't have an easy example to paste here.

A brief explanation is: Thingsboard is using default network, default network work only inside of docker. so containers can talk with each other but you won't be able to access Postgres outside the container unless you define a network for thingsboard to use that can access the outside
