### ISSUE TITLE
Docker Image for Raspberry Pi 3

### ISSUE THREAD

**Issue by sp7412** [thingsboard/thingsboard#2726]
Request for docker image that supports Raspberry Pi 3. I pulled the latest docker image and it doesn't support the Raspberry Pi architecture.

**Comment by Karabiy** [comment]
which exact error you are receiving?

**Comment by mborko** [comment]
I would also request a modified docker image for the rpi4 ... here is the error:
> standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by philprobinson84** [comment]
I would also love to see a Docker image supporting the Pi3/4.

**Comment by spa-sam** [comment]
Are there any results on docker for RP?

**Comment by SimonVleugels** [comment]
Still nothing?

**Comment by simonerom** [comment]
I need that too!

**Comment by davidmosna** [comment]
I need that too!

**Comment by waplet** [comment]
Would appreciate this. Maybe anyone has a "Dockerfile" to build for Raspberry PI?

**Comment by gustavovelascoh** [comment]
+1 here

**Comment by vitalikplus** [comment]
+1

**Comment by GuiMLS** [comment]
Up!

**Comment by Karabiy** [comment]
@zbeacon

**Comment by cudmore** [comment]
On a Raspberry Pi 4 with Raspian/Debian Buster, I get an error when trying to pull the docker in a docker-compose.yml

Pulling from command line

```
docker pull thingsboard/tb-postgres
```

Gives error:

```
Pulling mytb (thingsboard/tb-postgres:)...
latest: Pulling from thingsboard/tb-postgres
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Question: Is there a thingsboard/tb-postgres (or other) image available for a Raspberry Pi running debian/raspbian Buster?

my docker-compose.yml is:

```
version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: rabbitmq
      TB_QUEUE_RABBIT_MQ_USERNAME: YOUR_USERNAME
      TB_QUEUE_RABBIT_MQ_PASSWORD: YOUR_PASSWORD
      TB_QUEUE_RABBIT_MQ_HOST: localhost
      TB_QUEUE_RABBIT_MQ_PORT: 5672
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
```
