### ISSUE TITLE
ThingsBoard CE 2.5 values of "lastActivityTime" not update realtime (not according to sensor data)

### ISSUE THREAD

**Issue by itnas** [thingsboard/thingsboard#2766]
Sorry for my English
ThingsBoard CE 2.5 "lastActivityTime" not update according to sensor data

My sensor data is update every 1 second but the values of "lastAcivityTime" update/change/Refresh every 30 second

This problem not happen in ThingsBoard CE 2.4.3
![image](https://user-images.githubusercontent.com/2129863/81783803-17dee180-9526-11ea-9ab8-7122c9a37e2c.png)

**Comment by ashvayka** [comment]
Hi @itnas  This is related to separation of rule engine and core services in 2.5. We have made an improvement to update device active/inactive state and lastActivityTime periodically (only if there was an activity or device become inactive). This is configured using parameters from thingsboard.yml (or ENV variables in thingsboard.conf):

```yml
transport:
  sessions:
    inactivity_timeout: "${TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT:300000}"
    report_timeout: "${TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT:30000}"
```
