### ISSUE TITLE
Inconsistent server availability - USING MQTT

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3095]
Hi, 
When trying to use multiprocessing and threads to connect multiple clients to thingsboards (over mqtt), Im getting a variable amount of clients that do not connect because of (rc = 3, server unavailable). Is there any variable/limit that causes this?

Looking at my log files, i am having some allocation failures: See a portion of the allocation failure message
```
2020-07-14T14:38:30.366+0100: 1588.643: [GC (Allocation Failure) 2020-07-14T14:38:30.366+0100: 1588.644: [ParNew
Desired survivor size 2162688 bytes, new threshold 6 (max 6)
- age   1:    1409992 bytes,    1409992 total
: 37694K->2774K(38080K), 0.0055322 secs] 140673K->107305K(181776K), 0.0057250 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
Heap after GC invocations=314 (full 6):
 par new generation   total 38080K, used 2774K [0x0000000084400000, 0x0000000086d50000, 0x00000000990c0000)
  eden space 33856K,   0% used [0x0000000084400000, 0x0000000084400000, 0x0000000086510000)
  from space 4224K,  65% used [0x0000000086510000, 0x00000000867c5870, 0x0000000086930000)
  to   space 4224K,   0% used [0x0000000086930000, 0x0000000086930000, 0x0000000086d50000)
 concurrent mark-sweep generation total 143696K, used 104531K [0x00000000990c0000, 0x00000000a1d14000, 0x0000000100000000)
 Metaspace       used 127806K, capacity 135722K, committed 136328K, reserved 1169408K
  class space    used 15625K, capacity 17101K, committed 17348K, reserved 1048576K
}
```
Is this related in some way to not being able to connect all my devices (1,000 devices)? Im trying to try until 10,000 devices, but im not sure if there is a limit that prevents this.

**Comment by fjpa121197** [comment]
I tried with 2,000 devices. And in two times I tried, I got 91 rc = 3, and the last time I got 32 rc=3.

**Comment by Karabiy** [comment]
specify the hardware setup of yours
also, those can be so because of the default limits being set for the default installation, and there also limits for the live demo being set
refer to this link on api limits docs: https://thingsboard.io/docs/user-guide/api-limits/
the transport topic

**Comment by fjpa121197** [comment]
Hi, my hardware setup is the following: 
Proceessor: Intel Core i5-3570 CPU @3.40GHz x 4
RAM: 8GB
Disk Size 500GB

My installation is locally and I have changed the conf file to accepts more than 1000 messages per second and minute (for tenant). But I still get rc = 3 for a high amount of connections.
```
transport:
  sessions:
    inactivity_timeout: "${TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT:300000}"
    report_timeout: "${TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT:30000}"
  rate_limits:
    enabled: "${TB_TRANSPORT_RATE_LIMITS_ENABLED:false}"
    tenant: "${TB_TRANSPORT_RATE_LIMITS_TENANT:10000:1,200000:60}"
    device: "${TB_TRANSPORT_RATE_LIMITS_DEVICE:10:1,300:60}"

```
