### ISSUE TITLE
Failed to load configuration ui resources. [Bug] 

### ISSUE THREAD

**Issue by Heavenclone** [thingsboard/thingsboard#3175]
Description:
Recently updated from v2.3 to v3.0.1
When inspecting Rule Chain Nodes, Node UI fails to load.
![image](https://user-images.githubusercontent.com/68871020/88579806-a4267e00-d018-11ea-8d2e-27198edc3b38.png)

Setup:
   Thingsboard v3.0.1 hosted in an EC2 instance in AWS

**Comment by spasoye** [comment]
is there solution to this ? I installed v3.1.1 , started messing around with rule chains and sudenly this happened.
Any ideas? I have no idea how to trace this.

**Comment by chhein** [comment]
Got the same issue on Thingsboard v3.2.1
How do you resolved the issue ?
@Heavenclone 
@ashvayka 
@vvlladd28

**Comment by chhein** [comment]
We finally find the error, when using Traefik as IngressController the static routes in Thingsboard should not be stripped.

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefixRegex:
    regex:
      - "/api/v1/.*"
      #- "/static/rulenode/.*" // LEADS TO ERRORS IN RULECHAIN
      - "/api/v1/integrations.*"
      - "/index.html.*"
      #- "/static/.*" / LEADS TO ERRORS IN RULECHAIN
```

**Comment by mokhos** [comment]
Hi @chfxr 
We have the same problem here. I did what you said and commented out the `/static/rulenode/.*` part but it didn't work.
Would you please share your Traefik's ingress.

Thanks in advance

**Comment by toquelis** [comment]
Hello. A member of our Team was having this same issue after upgrade from v3.4.1 to v3.4.0 on a Professional edition instance. The issue disappeared after clearing cache on her Browser.  😄

**Comment by icebob** [comment]
We are facing the same issue with 3.4.0 and 3.4.1 and cache clearing, private/incognito browser doesn't solve it. Any ideas?

![image](https://user-images.githubusercontent.com/306521/188707869-7ec09fc6-f3c4-46ed-ae84-c96e6e6e48f4.png)

**Comment by toquelis** [comment]
Could it be that you have caching enabled on your reverse proxy between ThingsBoard and your browser? (nginx, haproxy)

**Comment by icebob** [comment]
Good idea, but we are using Kong ingress, but caching is not enabled.

**Comment by icebob** [comment]
The problem is that in the microservices arch, the [k8s ingress configures](https://github.com/thingsboard/thingsboard-ce-k8s/blob/5c4a9495f890e2f042341eb54bacf825992743dc/aws/microservices/receipts/http-load-balancer.yml#L21-L27) the `/static/rulenode/*` to the `tb-node`:

```yml
          - path: /static/rulenode/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080
```



But there is a JS file which matches this route and try to download it from tb-node instead of the `web-ui` node:

![image](https://user-images.githubusercontent.com/306521/190495280-dce330ae-843a-4902-b568-ba229c46af6d.png)
