### ISSUE TITLE
[Question] How to creat entity or update entity by Rule Engine

### ISSUE THREAD

**Issue by viccom** [thingsboard/thingsboard#3290]
**Component**

 * Rule Engine

**Description**

How to creat entity or update entity by Rule Engine ?

**Environment**

 * OS:  OS: ubuntu 18.04.4 LTS
 * ThingsBoard: 3.01

**Comment by Karabiy** [comment]
for those reasons you can use the REST API requests. For example, refer to the below. 
![image](https://user-images.githubusercontent.com/31805736/90021832-70a34f00-dcba-11ea-8a98-37b62d6ffa59.png)
the enrichment originator node can be used to fetch the values of the entity fields and then the rest api call can be used
![image](https://user-images.githubusercontent.com/31805736/90028098-f1b21480-dcc1-11ea-9b91-43c8d6c5f6ca.png)
you can use the attribute update widgets, though, you will need to split those processing, using different filtering to be pre-applied. 
It will also require to have the authorization process being handled, to receive the JWT_TOKEN and use the Rest API Calls to the ThingsBoard using the JWT_TOKEN. Those can be done with an additional Rest API Call request before the processing/on the processing. 
You can refer on how to proceed with the REST API requests on this link: https://thingsboard.io/docs/reference/rest-api/

**Comment by viccom** [comment]
Thank you for your answer, let me test it.

**Comment by viccom** [comment]
In my test, I use "rest api call" to get the entity and must use the setting "x-authorization", 

but the setting of "x-authorization" must know the user's token, and the token validity is 2 hours. 

Is there any other way to solve the problem of token timeliness is 2 hours.

**Comment by Karabiy** [comment]
you can adjust the parameter for the token. you can refer to the jwt topic in the thingsboard.yml for those. 
```
security:
  # JWT Token parameters
  jwt:
    tokenExpirationTime: "${JWT_TOKEN_EXPIRATION_TIME:9000}" # Number of seconds (2.5 hours)
    refreshTokenExpTime: "${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800}" # Number of seconds (1 week)
    tokenIssuer: "${JWT_TOKEN_ISSUER:thingsboard.io}"
    tokenSigningKey: "${JWT_TOKEN_SIGNING_KEY:thingsboardDefaultSigningKey}"
```
So that you can you can increase the tokenExpirationTime, though, you will still require to set the name and the password for the corresponding processing of the gaining of the token to be handled within the rule engine.
