### ISSUE TITLE
Docker Thingsboard PE container doesn´t run

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3315]
**Component**

 * Installation

**Description**

I use the following `docker-compose.yml` file to run my docker container with Thingsboard:

```
version: '2.2'
services:
  ThingsBoard:
    restart: always
    image: "store/thingsboard/tb-pe:3.1.0PE"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      TB_LICENSE_SECRET: "SomeLicense"
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
    volumes:
      - ~/.ThingsBoard-data:/data
      - ~/.ThingsBoard-logs:/var/log/thingsboard
```

But the dashboard doesn´t come up and I get the following output (see attachment).

[Log.txt](https://github.com/thingsboard/thingsboard/files/5074717/Log.txt)

How can I fix this issue?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.1.0PE
