### ISSUE TITLE
[Question] Function of security.basic.enabled

### ISSUE THREAD

**Issue by TrevorMuraro** [thingsboard/thingsboard#3416]
**Component**
Generic

**Description**
Starting with ThingsBoard 2.5, thingsboard.yml contains the property
```yml
security:
  basic:
    enabled: "${SECURITY_BASIC_ENABLED:false}"
```

The only reference I could find for this was Spring Boot's `security.basic.enabled`, which was removed in Spring Boot v2.0. However, ThingsBoard was already using a version of Spring Boot greater than v2.0.

What does this property do?

**Environment**

 * ThingsBoard: v2.5 and higher
