### ISSUE TITLE
[Bug] Installation fails

### ISSUE THREAD

**Issue by kunago** [thingsboard/thingsboard#3473]
**Describe the bug**
Installation of Thingsboard crashes, it results in fatal error due to a missing db "thingsboard"

**Your Server Environment**
* own setup
  * docker deployment (in-memory queue, tried also RabbitMQ with ever worse result)
  * ThingsBoard v3.1.1
  * in a docker container, host is Debian

**Your Client Environment**
_not needed for the bug description_

**Your Device**
* Connectivity
  * in-memory queue

**To Reproduce**
1. Start the docker image for the first time
2. The installatiton does not succeed because of a missing database

**Expected behavior**
I would expect the database to be created on the first run.

**Additional context**
* docker-compose.yml (chosen lines)
```
  thingsboard:
    image: thingsboard/tb-postgres
    env_file:
      - thingsboard.env
    expose:
      - 8080
      - 1883
      - 5683
    volumes:
      - /opt/lora/data/thingsboard:/data
      - /opt/lora/log/thingsboard:/var/log/thingsboard
    networks:
      backend:
        ipv4_address: X.X.X.X
    restart: always
```

* cat thingsboard.env
```
TB_QUEUE_TYPE=in-memory
```
* additional information
  * I chmod the mounted volumes properly (chmod -R 799:799)
  * the containers are exposed because I am using a proxy, which works fine
  * I did actually succeed eventually with the previous installation but I cannot replicate the steps, how I did it; I can create a DB with `createdb` command but it remains just an empty DB.
