### ISSUE TITLE
[Question] What is "Processing in isolated container" ?

### ISSUE THREAD

**Issue by mkrydik** [thingsboard/thingsboard#3563]
**Component**

 * Generic

**Description**

I can't figure out what the `Processing in isolated container` option is.
What is the impact of this option?
<img width="478" alt="screenshot 1" src="https://user-images.githubusercontent.com/57387361/95536290-a435f780-0a25-11eb-8551-dcf18b373a86.png">

When I enabled the `isolated container` option, I confirmed that `"Latest Telemetry"` was not displayed even though I sent telemetry data.
Is this the correct behavior?
<img width="1078" alt="screenshot 2" src="https://user-images.githubusercontent.com/57387361/95536609-5a014600-0a26-11eb-8e0b-b7f3b16009cf.png">

**Environment**

 * OS:  macOS Hgih Sierra 10.13.6
 * ThingsBoard: 3.0.0PE
 * Browser: Chrome 84.0.4147.125

**Comment by t0mmyz7** [comment]
I am so interested in this. I assume it has to do with running TB in
cluster mode.

**Comment by ashvayka** [comment]
Processing in isolated Rule Engine container works. When you use this option, you should start a separate rule-engine microservice and specify the tenant_id there. See thingsboard.yml:

```yml
...
service:
  type: "${TB_SERVICE_TYPE:monolith}" # monolith or tb-core or tb-rule-engine
  # Unique id for this service (autogenerated if empty)
  id: "${TB_SERVICE_ID:}"
  tenant_id: "${TB_SERVICE_TENANT_ID:}" # empty or specific tenant id.
```

So, you should put your specific tenant id (UUID that you may copy from tenant details) into TB_SERVICE_TENANT_ID.

This option allows you to completely isolate Rule Engine processing for a particular tenant. The messages are pushed to a separate queue, and if you do not launch the microservice, the main rule engine service (for non-isolated tenants) will not process it.
