### ISSUE TITLE
Problem with tb-gateway error...

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#361]
The configuration as indicated tb-gateway.yml

```
gateway:
  reporting:
    interval: 60000
  persistence:
    type: file
    path: storage
    bufferSize: 1000
  connection:
    host: "localhost"
    port: 1883
    retryInterval: 3000
    maxInFlight: 1000
    security:
      accessToken:Poo4AtvUV6nbAO818tsk
#      keystore: mqttclient.jks
#      keystorePassword: password
#      keystoreKeyAlias: clientalias
#      truststore: mqttclient.jks
#      truststorePassword: password

opc:
  enabled: false
  configuration: opc-config.json

mqtt:
  enabled: true
  configuration: mqtt-config.json
```

Errors

```
***************************
APPLICATION FAILED TO START
***************************
Description:

Binding to target TbConnectionConfiguration(host=localhost, port=1883, retryInterval=3000, maxInFlight=1000, security=null) failed:

    Property: gateway.connection.security
    Value: accessToken:Poo4AtvUV6nbAO818tsk
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.thingsboard.gateway.service.MqttGatewaySecurityConfiguration' for property 'security'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.thingsboard.gateway.service.MqttGatewaySecurityConfiguration' for property 'security': no matching editors or conversion strategy found
```

Someone could help me please
