### ISSUE TITLE
Prometheus metrics from things boards CE/PE

### ISSUE THREAD

**Issue by cnolick** [thingsboard/thingsboard#3692]
**Component**

* Installation

**Description**
I find in code  this config block
```yml
management:
  endpoints:
    web:
      exposure:
        # Expose metrics endpoint (use value 'prometheus' to enable prometheus metrics).
        include: '${METRICS_ENDPOINTS_EXPOSE:info}'
```
I tried  setup and check it, but I don't find traces prometheus, how to get metric in format prometheus? 

 * OS:  osx+docker
 * ThingsBoard: 3.1.1
 * Browser: safari:14.0
