### ISSUE TITLE
[Bug] Thingsboard CE 3.2.0 R does not restart in the docker-compose 

### ISSUE THREAD

**Issue by viktorbilousov** [thingsboard/thingsboard#3856]
I set up CE 3.2.0 following the instruction at https://thingsboard.io/docs/user-guide/install/docker/.  The first time the system is successfully setting up and running, but after conatainer restart I get the follow error 

```
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

docker-compose.yml

```
version: '2.2'
services:
  thingsboard:
    image: thingsboard/tb-postgres:3.2.0
    ports:
      - "8080:9090"       
      - "1885:1883"      
      - "5685:5683/udp"   
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data-compose:/data
      - ~/.mytb-logs-compose:/var/log/thingsboard
```

Steps to reproduce this error: 

```
sudo rm -rf ~/.mytb-*
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs

docker-compose up -d
# wait until  TB ready  
docker-compose down
docker-compose up -d 
```

**OS** : Ubuntu 20.04 LTS
**Docker** :  19.03.9
**docker-compose**  : 1.25.0,

logfile : [thingsboard.log](https://github.com/thingsboard/thingsboard/files/5704536/thingsboard.log)
