### ISSUE TITLE
[Bug] Telemetry sent from a gateway configured with a modbus connector does not seem to reach cassandra.

### ISSUE THREAD

**Issue by gzlz** [thingsboard/thingsboard#3955]
Telemetry sent from a gateway configured with a modbus connector does not seem to reach cassandra.
I'm not sure if the problem is after upgrading from version 3.1.1 to 3.2 since with version 3.1.1 I had not yet tried sending telemetry.

Server:
  -   On premise installation
  -   ThingsBoard 3.2
  -   Ubuntu Server 18.04.5 LTS

Device:
  - Gateway with modbus TCP/IP conector

The gateway works fine, it read from a Modbus PLC, I see in the PLC that the gateway is reading, but telemetry does not reach cassandra. I don´t see the device in the device list. If I try this gateway with the demo.thingsboard.com works fine, the device is created and the telemetry arrives.

This is the final of the thingsboard.log file. Seems like the ts_kv_latest_cf doesn´t exit.

![log](https://user-images.githubusercontent.com/19785703/104709258-fcfce680-571e-11eb-96aa-1075c686922d.PNG)

And filtered per ERROR:

![log_ERROR](https://user-images.githubusercontent.com/19785703/104712952-87dfe000-5723-11eb-9296-3756373bb7d4.PNG)

**Comment by ashvayka** [comment]
Hi @gzlz. Based on the error log, I suspect you have installed the system with the following parameters:
```yaml
database:
  ts_max_intervals: "${DATABASE_TS_MAX_INTERVALS:700}" # Max number of DB queries generated by single API call to fetch telemetry records
  ts:
    type: "${DATABASE_TS_TYPE:sql}" # cassandra, sql, or timescale (for hybrid mode, DATABASE_TS_TYPE value should be cassandra, or timescale)
  ts_latest:
    type: "${DATABASE_TS_LATEST_TYPE:sql}" # cassandra, sql, or timescale (for hybrid mode, DATABASE_TS_TYPE value should be cassandra, or timescale)
```

and then changed DATABASE_TS_LATEST_TYPE to Cassandra. In such a case, the Cassandra column family is not created and the writes are not successful. You can fix it by applying the "table" creation script manually: [schema-ts-latest.cql](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/cassandra/schema-ts-latest.cql) . Please make sure that the other tables mentioned in the [schema-ts.cql](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/cassandra/schema-ts.cql) are created as well. This will fix the issue. However, I also recommend to set DATABASE_TS_LATEST_TYPE to "sql" if you don't have more then 10 000 data points per second. This will make latest telemetry searchable via [entity filters](https://thingsboard.io/docs/user-guide/advanced-filters/).
