### ISSUE TITLE
[Bug] Kubernetes secrets get not recognized in Thingsboard node (FATAL: password authentication failed for user "<MYUSER>") 

### ISSUE THREAD

**Issue by ch9hn** [thingsboard/thingsboard#4100]
**Describe the bug**
When using Kubernetes secrets, the passwords which are being set via Kubernetes secrets get not recognized from Thingsboard Core.
 
**Your Server Environment**
Common Kubernetes Cluster
Version 1.19.7
Provider: Scaleway

**To Reproduce**
1. Create Kubernetes Secret with SPRING_DATASOURCE_PASSWORD

```
apiVersion: v1
kind: Secret
metadata:
  name: tb-node-secrets
  namespace: thingsboard
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: <SUPERSECURE BASE64 ENCODED PASSWORD>
```

  2. Mount secret in Thingsboard pod
 
```
...
        envFrom:
        - configMapRef:
            name: tb-node-cache-config
        - secretRef:
            name: tb-node-secrets
...
```
 
3. Apply config to cluster
4. Check if the Environment var is correctly set
`kubectl exec -it pod/tb-node-0 -n thingsboard -- echo $SPRING_DATASOURCE_PASSWORD`
Check successful, password is correct.
5. Check Logs of the Pod
 `org.postgresql.util.PSQLException: FATAL: password authentication failed for user "<MYUSER>"`
**Expected behavior**
Thingsboard node regcognize the password and connect via Database.
