### ISSUE TITLE
[Bug] Timeseries data is not deleted by ttl 

### ISSUE THREAD

**Issue by JonasRueck** [thingsboard/thingsboard#4120]
**Component**

 * Generic

**Description**

We have added the TTL-Parameter inside the thingsboard.yml as shown in below image.

![image](https://user-images.githubusercontent.com/58257724/108228203-ee9b5380-713e-11eb-9596-b1fb12f9977e.png)

If I understand the properties right timeseries data will be deleted in time x specified in execution_interval_ms and every timeseries data is deleted which is older than the time which is specified in ts_key_value_ttl.

So in my example every 30 Seconds all timeseries data which is older than 30 seconds will be deleted?

The problem is that the data is not deleted. I also tried to specify the ttl parameter on tenant level or on the save timeseries node, but that did not work, too.

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.2.1 CE
 * Browser: Google Chrome

**Comment by jblabd** [comment]
Hi JonasRueck,

I don't have a proper answer but here my experience.

I also added a TTL parameter in my _Save Timeserie_ node. I tried 60 seconds and I was excepting the data be deleted 60 seconds after, but it was not the case.

Then I found the following parameter into the Thingsboard configuration :
`sql.ttl.ts.execution_interval_ms |
SQL_TTL_TS_EXECUTION_INTERVAL |
86400000 |
The parameter to specify the period of execution TTL task for timeseries records. Value set in milliseconds. Default value corresponds to one day.`

It seems that the TTL task will only run once a day (default value) so when the task will run it will delete the data, I think.

**Comment by seikosantana** [comment]
I need some help, it is urgent.
I am running Thingsboard CE on a Raspberry Pi 4 and it ran out of space last night, i realized it is not purging old telemetries automatically, so i dig in about data retention.

Temporarily, i just cleaned up logs which is 800MB in size, and it might be full again in days.
I use Timescale, and now i set this in thingsboard.yml

```
timescale:
  chunk_time_interval: "${SQL_TIMESCALE_CHUNK_TIME_INTERVAL:604800000}"
  batch_threads: "${SQL_TIMESCALE_BATCH_THREADS:4}"
ttl:
  ts:
    enabled: "${SQL_TTL_TS_ENABLED: true}"
    execution_interval_ms: "${SQL_TTL_TS_EXECUTION_INTERVAL:60000}"
    ts_key_value_ttl: "${SQL_TTL_TS_TS_KEY_VALUE_TTL:10520000}"
```

I've restarted Thingsboard service, and the disk is still as full as before. What am i missing?
