### ISSUE TITLE
[Bug] Unable to set up SSL context. Reason: resource /etc/thingsboard/certs/keystore.jks not found

### ISSUE THREAD

**Issue by chhein** [thingsboard/thingsboard#4216]
**Describe the bug**
When using MQTT SSL on thingsboard-mqtt-transport, the keystore file generated by cert-manager get not accepted.
**Your Server Environment**

Own Kubernetes Setup:
Versions:
Kubernetes: v1.19.7
Cert Manager: v1.1.0 (via Helm)
ThingsBoard Version: tb-pe-mqtt-transport:3.2.1PE

**Your Device**

* Connectivity
  * MQTT
* Device vendor and model

**To Reproduce**

*Configs:*

*Cert-Manager Resource:*

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tb-mqtt-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tb-mqtt-cert
  namespace: tb-dev
spec:
  secretName: tb-mqtt-cert
  commonName: tb-mqtt-cert
  hostname:
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: tb-mqtt-selfsigned
    kind: Issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: jkspw
        name: jkspw
    jks:
      create: true
      passwordSecretRef:
        key: jkspw
        name: jkspw

```

Thingsboard MQTT Transport Resource:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-mqtt-transport
  namespace: tb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-mqtt-transport
  template:
    metadata:
      labels:
        app: tb-mqtt-transport
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: fix-permissions
          image: debian:buster-slim
          command: ["/bin/bash", "-c"]
          args:
            - cp -RL /etc/keyfile-raw/* /etc/thingsboard/certs/;
              chown -R 799:799 /etc/thingsboard/certs/;
              chmod 400 /etc/thingsboard/certs/*;
              ls -laL /etc/thingsboard/certs/;
          volumeMounts:
            - name: mqtt-cert-data
              mountPath: /etc/thingsboard/certs/
            - name: tb-mqtt-cert
              mountPath: /etc/keyfile-raw
          securityContext:
            runAsUser: 0
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-mqtt-transport:3.2.1PE
        resources:
          limits:
            cpu: 500m
            memory: 1000M
          requests:
            cpu: 250m
            memory: 500M
        ports:
        - containerPort: 1883
          name: mqtt
        env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_QUEUE_TYPE
          value: "kafka"
        - name: MQTT_BIND_ADDRESS
          value: "0.0.0.0"
        - name: MQTT_BIND_PORT
          value: "1883"
        - name: MQTT_TIMEOUT
          value: "10000"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        - name: MQTT_SSL_ENABLED
          value: "true"
        - value: MQTT_SSL_PROTOCOL
          name: "TLSv1"
        - name: MQTT_SSL_KEY_STORE
          value: "/etc/thingsboard/certs/keystore.jks"
        - name: MQTT_SSL_KEY_STORE_TYPE
          value: JKS
        - name: MQTT_SSL_KEY_PASSWORD
          value: ""
#        - name: MQTT_SSL_KEY_STORE_PASSWORD
#          value: ""
        - name: MQTT_SSL_KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jkspw
              key: jkspw
#        - name: MQTT_SSL_KEY_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: jkspw
#              key: jkspw
        readinessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 1883
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 20
          tcpSocket:
            port: 1883
        securityContext:
          runAsUser: 799
          runAsGroup: 799
        volumeMounts:
          - name: mqtt-cert-data
            mountPath: /etc/thingsboard/certs
          - name: tb-mqtt-transport-config
            mountPath: /config
      volumes:
        - name: tb-mqtt-transport-config
          configMap:
            name: tb-mqtt-transport-config
            items:
              - key: conf
                path: tb-mqtt-transport.conf
              - key: logback
                path: logback.xml
        - name: tb-mqtt-cert
          secret:
            secretName: tb-mqtt-cert
            items:
              - key: keystore.jks
                path: keystore.jks
        - name: mqtt-cert-data
          emptyDir: {}
      restartPolicy: Always

```

Get into the pod and check file:
```
kubectl exec -it deploy/tb-mqtt-transport -- bash
keytool -list -v -keystore /etc/thingsboard/certs/keystore.jks
Enter keystore password:  <ENTERED PASSWORD>
################################################

Keystore type: jks
Keystore provider: SUN

Your keystore contains 2 entries

Alias name: certificate
Creation date: Mar 8, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=tb-mqtt-cert
Issuer: CN=tb-mqtt-cert
Serial number: XXX
Valid from: Mon Mar 08 16:35:14 UTC 2021 until: Sun Jun 06 16:35:14 UTC 2021
Certificate fingerprints:
	 MD5:  XXX
	 SHA1: XXX
	 SHA256: XXX
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: XXX Criticality=true
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#2: ObjectId: XXX Criticality=true
KeyUsage [
  DigitalSignature
  Key_Encipherment
]



*******************************************
*******************************************


Alias name: ca
Creation date: Mar 8, 2021
Entry type: trustedCertEntry

Owner: CN=tb-mqtt-cert
Issuer: CN=tb-mqtt-cert
Serial number: XXX
Valid from: XXX
Certificate fingerprints:
	 MD5: XXX
	 SHA1: XXX
	 SHA256: XXX
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: XXX Criticality=true
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#2: ObjectId: XXX Criticality=true
KeyUsage [
  DigitalSignature
  Key_Encipherment
]



*******************************************
*******************************************
```
Error Log:
```
2021-03-08 16:39:14,625 [nioEventLoopGroup-3-2] ERROR o.t.s.t.mqtt.MqttSslHandlerProvider - Unable to set up SSL context. Reason: resource /etc/thingsboard/certs/keystore.jks not found.
java.lang.IllegalArgumentException: resource /etc/thingsboard/certs/keystore.jks not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.common.io.Resources.getResource(Resources.java:195)
	at org.thingsboard.server.transport.mqtt.MqttSslHandlerProvider.getSslHandler(MqttSslHandlerProvider.java:93)
	at org.thingsboard.server.transport.mqtt.MqttTransportServerInitializer.initChannel(MqttTransportServerInitializer.java:56)
	at org.thingsboard.server.transport.mqtt.MqttTransportServerInitializer.initChannel(MqttTransportServerInitializer.java:43)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-03-08 16:39:14,628 [nioEventLoopGroup-3-2] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x56d0e256, L:/100.64.211.96:1883 - R:/10.19.32.85:44744]

```
**Expected behavior**
Thingsboard MQTT Transport should load keystore.jks from file

**Comment by chhein** [comment]
**Solved**
Ive solved this issue by myself.
1. The variable MQTT_SSL_KEY_STORE must have the plain filename e.g. mqttserver.jks
An absolute Path is not valid and leads to this error message.
2. The mqttserver.jks file needs to be places inside the following folder for the tb-mqtt-microservice:
 /etc/tb-mqtt-transport/conf/
 Put it together:
```
         volumeMounts:
          - name: mqtt-cert-data
            mountPath: /etc/tb-mqtt-transport/conf/
          - name: tb-mqtt-transport-config
            mountPath: /config
      volumes:
        - name: tb-mqtt-transport-config
          configMap:
            name: tb-mqtt-transport-config
            items:
              - key: conf
                path: tb-mqtt-transport.conf
              - key: logback
                path: logback.xml
                        - name: tb-mqtt-cert
          secret:
            secretName: mqttserverjks
            items:
              - key: mqttserver.jks
                path: mqttserver.jks
```
Init Container for permissions
```
      initContainers:
        - name: fix-permissions
          image: debian:buster-slim
          command: ["/bin/bash", "-c"]
          args:
            - export KEYPATH=/etc/tb-mqtt-transport/conf/;
              cp -RL /etc/keyfile-raw/* $KEYPATH;
              chown -R 799:799 $KEYPATH;
              chmod 0400 $KEYPATH*;
              ls -laL $KEYPATH;
          volumeMounts:
            - name: mqtt-cert-data
              mountPath: /etc/tb-mqtt-transport/conf/
            - name: tb-mqtt-cert
              mountPath: /etc/keyfile-raw
          securityContext:
            runAsUser: 0
```

I hope this helps others !
/close
