### ISSUE TITLE
[Question] How to enable MQTT over SSL in Thingsboard PE V3.2.2 Docker on promise (vps)

### ISSUE THREAD

**Issue by nowherex** [thingsboard/thingsboard#4970]
Hi, I'm trying to enable MQTT over SSL, I'm currently generating the https certificate for my domain with letsencrypt (using the official [guide for HAProxy Load Balancer](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/)), how should I configure to allow mqtts in ThingsBoard PE using Docker ? I appreciate any help, tanks.

Environment

OS: Ubuntu 20.04 (64 Bit)
ThingsBoard: Thingsboard PE V3.2.2
Browser: Google Chrome

**Comment by marulitua** [comment]
Thingsboard is a java app, so we have to add certificate to java key store.
By default thingsboard will look for `mqttserver.jks` under configuration directory.
Add the following code to your letsencrypt renewal cron.

```
LOCATION="/home/manobo/manobo-docker"
PASS="YOURPASSWORD"
CERT_LOCATION="/etc/letsencrypt/live/yourdomain.com"

for i in "$LOCATION/thingsboard/conf/mqttserver.*"; do
    rm $i;
done

# create PKCS 12 archive
openssl pkcs12 -export \
	-in "$CERT_LOCATION/cert.pem" \
	-inkey "$CERT_LOCATION/privkey.pem" \
	-CAfile "$CERT_LOCATION/fullchain.pem" \
	-out "$LOCATION/thingsboard/conf/mqttserver.p12" \
	-name mqttserver \
	-caname "Let's Encrypt Authority X3" \
	-password "pass:$PASS"

# create java keystore from pkcs12 archive
docker run -it --rm -v "$LOCATION/thingsboard/conf:/cert" -w /cert thingsboard/openjdk8 bash -c "keytool -importkeystore -deststorepass $PASS -destkeypass $PASS -destkeystore mqttserver.jks -srckeystore mqttserver.p12 -deststoretype pkcs12 -srcstorepass $PASS -alias mqttserver"

# allow thingsboard to access keystore file 
chown 799:799 $LOCATION/thingsboard/conf/mqttserver.jks

```
Now we have to specify the keystore password on thingsboard

```
  thingsboard:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "4007:9090"
      - "1883:1883"
      - "8883:8883"
      - "5683:5683/udp"
    environment:
      MQTT_SSL_KEY_PASSWORD: YOURPASSWORD
      MQTT_SSL_KEY_STORE_PASSWORD: YOURPASSWORD
      MQTT_SSL_ENABLED: "true"
      MQTT_BIND_PORT: 8883
    volumes:
      - ./thingsboard/data:/data
      - ./thingsboard/conf:/usr/share/thingsboard/conf
```
