### ISSUE TITLE
Issue cancelled.

### ISSUE THREAD

**Issue by pmdscully** [thingsboard/thingsboard#4984]
* Local firewall problem. Not thingsboard related. - Closing Issue.

**Comment by pmdscully** [comment]
A little searching discovered the cross-origin access configuration in [/server/config/MvcCorsProperties.java](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/config/MvcCorsProperties.java) and [thingsboard.yml#L440](https://github.com/thingsboard/thingsboard/blob/940c81b095a33810dc7927b29bf7f7213dca29ca/application/src/main/resources/thingsboard.yml#L440), suggests that external access to the Web UI is allowed by default. The same config applies for the 3.2.2 release.

```
# spring CORS configuration
spring.mvc.cors:
  mappings:
    # Intercept path
    "[/api/**]":
      #Comma-separated list of origins to allow. '*' allows all origins. When not set,CORS support is disabled.
      allowed-origins: "*"
      #Comma-separated list of methods to allow. '*' allows all methods.
      allowed-methods: "*"
      #Comma-separated list of headers to allow in a request. '*' allows all headers.
      allowed-headers: "*"
      #How long, in seconds, the response from a pre-flight request can be cached by clients.
      max-age: "1800"
      #Set whether credentials are supported. When not set, credentials are not supported.
      allow-credentials: "true"
```
