### ISSUE TITLE
TB-3.3.2-PE: Kubernetes license persistence doesnt work

### ISSUE THREAD

**Issue by ch9hn** [thingsboard/thingsboard#5368]
Hello,
as mentioned here: #2437,
there are an issue with the License persistence in Kubernetes.
The release notes mentioned, that the problem is fixed: https://thingsboard.io/docs/reference/releases/#thingsboard-pe-13
_Persistent volumes for k8s deployments to store license data;_

Unfortunately the feature doesn't work in our Deployment and we get the same errors like in #2437. 
Every time, when the TB Node crashes, the License Instance in the Portal needs to be deleted manually. This is not the way we like to go for a automated Kubernetes environment.

Our Kubernetes Manifest:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-node
spec:
  serviceName: tb-node
  replicas: 1
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: tb-node
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      volumes:
        - name: tb-node-data
          persistentVolumeClaim:
            claimName: tb-node-license-pv-claim
        - name: tb-node-config
          configMap:
            name: tb-node-config
            items:
              - key: conf
                path: thingsboard.conf
              - key: logback
                path: logback.xml
        - name: secret-volume
          configMap:
            name: postgresrootca
      securityContext:
        runAsUser: 799
        runAsNonRoot: true
        fsGroup: 799
      imagePullSecrets:
        - name: regcred
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-node:3.2.2PE
        resources:
          limits:
            cpu: 1000m
            memory: 1.75Gi
          requests:
            cpu: 800m
            memory: 1.25Gi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: rpc
        env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - mountPath: /config
            name: tb-node-config
          - mountPath: /data
            name: tb-node-data
        readinessProbe:
          httpGet:
            path: /login
            port: http
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 360
          timeoutSeconds: 10
      restartPolicy: Always

```
The PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-node-license-pv-claim
  labels:
    app: tb-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
```

Thingsboard Configmap:
```

apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-node-config
  labels:
    name: tb-node-config
data:
  conf: |
      export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data"
      export JAVA_OPTS="$JAVA_OPTS -Xloggc:/var/log/thingsboard/${TB_SERVICE_ID}/gc.log -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/thingsboard/${TB_SERVICE_ID}/heapdump.bin -XX:+PrintGCDetails -XX:+PrintGCDateStamps"
      export JAVA_OPTS="$JAVA_OPTS -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10"
      export JAVA_OPTS="$JAVA_OPTS -XX:GCLogFileSize=10M -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
      export JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=10000 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSParallelInitialMarkEnabled"
      export JAVA_OPTS="$JAVA_OPTS -XX:+CMSEdenChunksRecordAlways -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+ExitOnOutOfMemoryError"
      export LOG_FILENAME=thingsboard.out
      export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
  logback: |
      <!DOCTYPE configuration>
      <configuration scan="true" scanPeriod="10 seconds">

          <appender name="fileLogAppender"
                    class="ch.qos.logback.core.rolling.RollingFileAppender">
              <file>/var/log/thingsboard/${TB_SERVICE_ID}/thingsboard.log</file>
              <rollingPolicy
                      class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                  <fileNamePattern>/var/log/thingsboard/${TB_SERVICE_ID}/thingsboard.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                  <maxFileSize>100MB</maxFileSize>
                  <maxHistory>30</maxHistory>
                  <totalSizeCap>3GB</totalSizeCap>
              </rollingPolicy>
              <encoder>
                  <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
              </encoder>
          </appender>

          <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
              <encoder>
                  <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
              </encoder>
          </appender>

          <logger name="org.thingsboard.server" level="INFO" />
          <logger name="com.google.common.util.concurrent.AggregateFuture" level="OFF" />

          <root level="INFO">
              <appender-ref ref="fileLogAppender"/>
              <appender-ref ref="STDOUT"/>
          </root>

      </configuration>
```
