### ISSUE TITLE
Connection refused when stop and start container [Bug] 

### ISSUE THREAD

**Issue by SilkyChickn** [thingsboard/thingsboard#6129]
**Describe the bug**
The thingsboard container crashes , when stopping and then starting the container again.

**Your Server Environment**

own setup
  * docker deployment
  * thingsboard/tb-postgres container
  * Linux 4.4.59+ x86_64

**To Reproduce**
1. Start the container with `docker-compose up -d`
2. After login page is shown, stop with `docker-compose stop`
3. Start again with `docker-compose start`
4. Crash

**Expected behavior**
Container should start again without any problems

**Error log**
https://pastebin.com/azWq7cdL

**Compose file**
```
version: '2.2'
services:
    mytb:

        restart: unless-stopped
        image: "thingsboard/tb-postgres"

        ports:
            - "9090:8080" # Webinterface ports
            - "1884:1883" # MQTT port
            - "7070:7070" # nRPC port
            - "5683-5688:5683-5688/udp"

        environment:
            TB_QUEUE_TYPE: in-memory

        volumes:
            - /var/services/homes/core.master/data:/data
            - /var/services/homes/core.master/logs:/var/log/thingsboard
```
