### ISSUE TITLE
[Question] How can thingsboard gateway connect multiple OPC servers?

### ISSUE THREAD

**Issue by bggmjxh** [thingsboard/thingsboard#6355]
The usage scenario is as follows: each device has an independent OPC server. Now I can correctly collect the device through the thingsboard gateway, but opcua In the configuration of JSON, the address of an OPC server corresponding to each device cannot be configured.
In the seemingly TB configuration, the "opc-ua" scenario only supports one server corresponding to multiple devices.
How can I configure the gateway to support one configuration and access all devices?

I need to configure an array "server"？
or
I need to configure multiple "opcua. json"

**Comment by devaskim** [comment]
You need to move this question to thingsboad-gateway project.
But I try to answer. You can create multiple configuration files opcua1. json, opcua2. json, opcua3. json and link each of them to corresponding OPC UA connector in the gateway configuration file. For example:
```yaml
connectors:
  -
    name: 1 OPC
    type: opcua
    configuration: opcua1.json
  -
    name: 2 OPC
    type: opcua
    configuration: opcua2.json
```
