### ISSUE TITLE
disabling unused transport microservices (coap,snmp, lwm2m) ?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#6479]
Hello

using cluster thingsboard PE setup with docker-compose - basic configuration

trying to save some system resources, can I easily disable unused transport services? I am not using coap, lwm2m and snmp at the moment. each is taking about 1.3GB of RAM

Is there a way to disable them in the config without having to comment out a bunch of lines in docker-compose.yml?

![image](https://user-images.githubusercontent.com/31729091/165147922-631ab2fb-1fc3-4e8f-a8c5-5bb0d3a1383e.png)

**Comment by devaskim** [comment]
Try to use environment variables, for example, [LWM2M_ENABLED](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L740) separately or in Docker .env file and then [forward these variables](https://stackoverflow.com/questions/29377853/how-to-use-environment-variables-in-docker-compose/50201232#50201232) into your container.

**Comment by t0mZ4** [comment]
hi @devaskim 

thanks, so what I ended up doing is adding "scale: 0" for those 3 services

i don't see any errors, should I expect any if I manually disable coap,lwm2m and snmp if they are not in-use? Will tb-node look for them or something?

for example:

```
tb-coap-transport:
    **scale: 0**
    restart: always
    image: "${DOCKER_REPO}/${COAP_TRANSPORT_DOCKER_NAME}:${TB_VERSION}"
    ports:
      - "5683:5683/udp"
    environment:
      TB_SERVICE_ID: tb-coap-transport
    env_file:
      - ../tb-coap-transport.env
    volumes:
      - ../tb-transports/coap/conf:/config
      - ../tb-transports/coap/log:/var/log/tb-coap-transport
    depends_on:
      - zookeeper
```

**Comment by ban2derlog** [comment]
Hello, in docker-compose cluster, if you change only Scale parameter for Transport containers, you can still receive errors in logs if try to create device with using transport that doesn't have valid pods.
For complete remove from ThingsBoard transport you need to add [Configuration Parameters](https://thingsboard.io/docs/user-guide/install/config/) from Environment Variable column to **docker-compose.yml** in section where is ThingsBoard Service configuration, as below:
```
tb-core:  **or**  tb-monolith:
  restart: always
  image: "thingsboard/tb-pe:3.3.4.1PE"
  environment:
    ...
    MQTT_ENABLED: false 
```

P.S. If you don't want to delete or comment strings with transport services in default docker-compose.yml - then to resolve resources you made right that change **Scale:** to **0** . In this case ThingsBoard Transport configuration still persists in Docker Compose and won't create a container, but if you add to docker-compose.yml previously mentioned parameters - ThingsBoard container won't even try to connect and even if you try to create a Device on UI on disabled Transport, you will only receive error on UI, but not in logs.
