### ISSUE TITLE
[Feature Request] upgrade kafkajs": "^2.0.2"

### ISSUE THREAD

**Issue by smatvienko-tb** [thingsboard/thingsboard#6750]
**Is your feature request related to a problem? Please describe.**
Do major **kafkajs** upgrade up to 2.0.2

**Describe the solution you'd like**
Follow [migration guide](https://kafka.js.org/docs/migration-guide-v2.0.0)

**Describe alternatives you've considered**
No alternative suggested

**Additional context**
It needs to be hard tested because it is vital for many ThingsBoard setups

**Comment by smatvienko-tb** [comment]
The testing was performed on local Kubernetes cluster (Minikube)
The msg rate is 15k/sec generated by the performance-test app
The tested image is `thingsboard/tb-js-executor:3.4.0-SNAPSHOT`
Kafka cluster x3 nodes from `bitnami/kafka:3.2.0-debian-10-r4` 
![image](https://user-images.githubusercontent.com/79898499/174429761-98dac58b-1b2e-414b-abc1-4bd1ca559d86.png)
Total 6 tb-js-executor in the cluster, approximate executions rate is 2.5k/sec per executor
![image](https://user-images.githubusercontent.com/79898499/174429813-fc8c070c-bb61-46d8-970c-6429f171220d.png)
The reliability is just fine: more than 100 million executions without restart.
No Kafka lag until CPU is enough to handle the load.
![image](https://user-images.githubusercontent.com/79898499/174430067-477ccc04-2f93-459a-bab7-37a994712ea4.png)
ThingsBoard's API usage stats shows the total executions
![image](https://user-images.githubusercontent.com/79898499/174430175-24785588-44af-4392-abf4-8b3169a81c0e.png)
Queue stats:
![image](https://user-images.githubusercontent.com/79898499/174430280-94a0eaf2-bad2-40bb-af87-c86fdc1cf3a7.png)
Rule chain:
![image](https://user-images.githubusercontent.com/79898499/174430357-9fccd571-c975-41eb-b329-bdd3932e0749.png)
Script rule node:
![image](https://user-images.githubusercontent.com/79898499/174430465-8e74ae7f-d9f4-4559-a2fe-920643af428f.png)
Here is the actual config for js-executors 
```bash
cat > tb-js-executor.yml
```
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-js-executor
spec:
  serviceName: tb-js-executor
  replicas: 6
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: tb-js-executor
  template:
    metadata:
      labels:
        app: tb-js-executor
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - tb-js-executor
                topologyKey: kubernetes.io/hostname
      containers:
        - name: tb-js-executor
          imagePullPolicy: Always
          image: sevlamat/tb-js-executor:3.4.0-SNAPSHOT
          resources:
            limits:
              cpu: "1"
              memory: 400Mi
            requests:
              cpu: "100m"
              memory: 100Mi
          ports:
            - containerPort: 8888
              name: http # /livenessProbe
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SLOW_QUERY_LOG_MS
              value: "100.000"
            - name: SCRIPT_STAT_PRINT_FREQUENCY
              value: "10000"
            - name: SCRIPT_BODY_TRACE_FREQUENCY
              value: "1000000"
            - name: SLOW_QUERY_LOG_BODY
              value: "false"
            - name: TB_KAFKA_LINGER_MS
              value: "100"
            - name: TB_KAFKA_BATCH_SIZE
              value: "250"
            - name: TB_KAFKA_COMPRESSION_TYPE
              value: "gzip"
            - name: SCRIPT_USE_SANDBOX
              value: "false"
          envFrom:
            - configMapRef:
                name: tb-cluster-stack-config
          startupProbe:
            httpGet:
              path: /livenessProbe
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 7
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
      restartPolicy: Always
---
```
