### ISSUE TITLE
[Bug] js-executor consumes about 5% vCPU when idle

### ISSUE THREAD

**Issue by smatvienko-tb** [thingsboard/thingsboard#6822]
**Describe the bug**
js-executor consumes about 5% vCPU core when **idle**
When 20 replicas are deployed it comes to about 100% of vCPU.
Most systems have a multiple vCPU and the problem may not even be noticed.

Here is the screenshot with the problem:
![image](https://user-images.githubusercontent.com/79898499/175573257-619a491c-ce13-4c70-93c4-8ca4e7fb20eb.png)

**Your Server Environment**
Js executors run in a docker environment with default settings. 
Kafka and Zookeeper were provided. 
ThingsBoard stopped. 
No Kafka lag. 
No new messages.
![image](https://user-images.githubusercontent.com/79898499/175573961-4985c2e5-5460-4036-9b27-b9aac4da1e55.png)
tb-js-executor version 3.4.0-SNAPSHOT, branch [develop/3.4](https://github.com/thingsboard/thingsboard/commits/develop/3.4) on Jun 24 2022
![image](https://user-images.githubusercontent.com/79898499/175574509-61699632-5269-4e86-94d3-89d7438a5c20.png)

**To Reproduce**
'cat > docker-compose.yml'
```
version: '2.2'
services:
  tb-js-executor1:
    network_mode: "host"
    restart: always
    image: "thingsboard/tb-js-executor:latest"
    environment:
      HTTP_PORT: "8881"
  tb-js-executor2:
    network_mode: "host"
    restart: always
    image: "thingsboard/tb-js-executor:latest"
    environment:
      HTTP_PORT: "8882"
  tb-js-executor3:
    network_mode: "host"
    restart: always
    image: "thingsboard/tb-js-executor:latest"
    environment:
      HTTP_PORT: "8883"
```
`docker-compose up`

**Expected behavior**
Expected CPU zero-usage on idle.
