### ISSUE TITLE
[Bug] Upgrading from v3.3.4.1 to  v3.4.x errors during boot up

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#7141]
While upgrading the thingsboard from v3.3.4.1 to v3.4.0 or v3.4.1, I got error related with 

Here is the log for the error message:
```
Starting Postgresql...
mytb_1  | waiting for server to start....2022-08-23 20:50:13.195 UTC [12] LOG:  starting PostgreSQL 12.12 (Debian 12.12-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
mytb_1  | 2022-08-23 20:50:13.196 UTC [12] LOG:  listening on IPv4 address "127.0.0.1", port 5432
mytb_1  | 2022-08-23 20:50:13.196 UTC [12] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
mytb_1  | 2022-08-23 20:50:13.196 UTC [12] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
mytb_1  | 2022-08-23 20:50:13.202 UTC [12] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mytb_1  | 2022-08-23 20:50:13.223 UTC [13] LOG:  database system was shut down at 2022-08-23 20:50:12 UTC
mytb_1  | 2022-08-23 20:50:13.229 UTC [12] LOG:  database system is ready to accept connections
mytb_1  |  done
mytb_1  | server started
mytb_1  | Creating database...
mytb_1  | 2022-08-23 20:50:13.383 UTC [30] ERROR:  database "thingsboard" already exists
mytb_1  | 2022-08-23 20:50:13.383 UTC [30] STATEMENT:  CREATE DATABASE thingsboard
mytb_1  | ERROR:  database "thingsboard" already exists
mytb_1  | Postgresql is ready
mytb_1  | Starting ThingsBoard installation ...
mytb_1  | [0.005s][warning][logging] Output options for existing outputs are ignored.
mytb_1  |   ______    __      _                              ____                               __
mytb_1  |  /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
mytb_1  |   / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
mytb_1  |  / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
mytb_1  | /_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
mytb_1  |                               /____/
mytb_1  | 
mytb_1  |  ===================================================
mytb_1  |  :: ThingsBoard ::       (v3.4.1)
mytb_1  |  ===================================================
mytb_1  | 
mytb_1  | Starting ThingsBoard Installation...
mytb_1  | Installing DataBase schema for entities...
mytb_1  | Installing SQL DataBase schema part: schema-entities.sql
mytb_1  | Unexpected error during ThingsBoard installation!
mytb_1  | org.postgresql.util.PSQLException: ERROR: insert or update on table "ota_package" violates foreign key constraint "fk_device_profile_ota_package"
mytb_1  |   Detail: Key (device_profile_id)=(de51f8a0-1461-11ec-baeb-5b4d3d703167) is not present in table "device_profile".
mytb_1  |   Where: SQL statement "ALTER TABLE ota_package
mytb_1  |                 ADD CONSTRAINT fk_device_profile_ota_package
mytb_1  |                     FOREIGN KEY (device_profile_id) REFERENCES device_profile (id)
mytb_1  |                         ON DELETE CASCADE"
mytb_1  | PL/pgSQL function inline_code_block line 4 at SQL statement
mytb_1  |       at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
mytb_1  |       at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
mytb_1  |       at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
mytb_1  |       at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
mytb_1  |       at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
mytb_1  |       at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
mytb_1  |       at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
mytb_1  |       at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
mytb_1  |       at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
mytb_1  |       at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
mytb_1  |       at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:63)
mytb_1  |       at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
mytb_1  |       at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:247)
mytb_1  |       at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mytb_1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mytb_1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytb_1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
mytb_1  |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
mytb_1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
mytb_1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
mytb_1  |       at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
mytb_1  | Unexpected error during ThingsBoard installation!
mytb_1  | ERROR: ThingsBoard is not installed
mytb_1  | 2022-08-23 20:50:59.519 UTC [12] LOG:  received fast shutdown request
mytb_1  | waiting for server to shut down....2022-08-23 20:50:59.522 UTC [12] LOG:  aborting any active transactions
mytb_1  | 2022-08-23 20:50:59.528 UTC [12] LOG:  background worker "logical replication launcher" (PID 19) exited with exit code 1
mytb_1  | 2022-08-23 20:50:59.528 UTC [14] LOG:  shutting down
mytb_1  | 2022-08-23 20:50:59.547 UTC [12] LOG:  database system is shut down
mytb_1  |  done
mytb_1  | server stopped
```

I'm using ubuntu 22.04 with postgressql 12.12. My docker-compose.yml file is here:
```
version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres:3.4.1"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SSL_ENABLED: "false"
#      SSL_PEM_CERT: "/data/certificate.crt"
#      SSL_PEM_KEY: "/data/private.key"
#      SSL_CREDENTIALS_TYPE: "PEM"
      
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_DRIVER_CLASS_NAME: "org.postgresql.Driver"

      SPRING_DATASOURCE_URL: jdbc:postgresql://tb2.molisens.com:5432/things
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE: 3
      AUDIT_LOG_ENABLED : "false"
      SQL_TTL_EVENTS_ENABLED : "false"
      #SQL_TTL_EVENTS_EVENTS_TTL: 10
      #SQL_TTL_EVENTS_DEBUG_EVENTS_TTL : 15



    volumes:
      - /home/ubuntu/.mytb-data:/data
      - /home/ubuntu/.mytb-logs:/var/log/thingsboard
```

 I have a working database with thingsboard version 3.3.3, v3.3.4.0 and v3.3.4.1 already. 

I have also tested with v3.4.0 and got the same error.
