### ISSUE TITLE
[Bug]  Has the PE version of Thingsboard's mobile application been discontinued?

### ISSUE THREAD

**Issue by sarguments** [thingsboard/thingsboard#7148]
After the 3.4 version update, the problem of not being able to log in to the cloud version has been neglected for several weeks.
I've been told that I just need to edit the following part of pubspec.yml, but it doesn't work.

before
```
  thingsboard_pe_client: 1.0.3
```

after
```
  thingsboard_pe_client:
    git:
      url: git@github.com:thingsboard/dart_thingsboard_pe_client.git
      ref: master
```
