### ISSUE TITLE
[Question] Thingsboard does not stop when receiving SIGTERM

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#7233]
**Component**

 * Generic

**Description**

I am using docker-compose setup on ubuntu
```
mytb:
    restart: always
    stop_grace_period: 4m
    image: "thingsboard/tb-cassandra"
...
```

By default, `docker-compose stop` sends SIGTERM and wait for 10s, before sending SIGKILL to forcefully kill the container. I have increased the timeout to 4 minutes to simulate the problem.

After issuing `docker-compose stop`, mytb container still continues to run normally until it hits 4 minute timeout and is forcefully kill. This is bad for the database as it will result in unclean state.

Why does it not properly shut down thingsboard? Am I doing it wrong?

**Environment**
 * OS:  ubuntu 20.04
 * ThingsBoard: 3.3.3
