### ISSUE TITLE
[Question] How to Grafana single non-cluster Docker image

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7307]
There is [official docs](https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/#step-6-enable-monitoring-optional) how to enable monitoring for cluster setup. But how to do the same for single Postgres-based Docker TB image?

**Comment by devaskim** [comment]
Add several *METRICS_* * environment variables to `docker_compose.yml`:

```lang:yaml
  thingsboard:
    image: "thingsboard/tb-postgres"
    container_name: thingsboard
    hostname: thingsboard
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
      - "1883:1883"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
      METRICS_ENABLED: "true"
      METRICS_ENDPOINTS_EXPOSE: prometheus
    volumes:
      - ./data:/data
      - ./logs:/var/log/thingsboard
```
And `prometheus.yml`
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'thingsboard'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'YOUR_THINGSBOARD_HOST_OR_IP:8080' ]

```
