### ISSUE TITLE
[Feature Request] TBEL script engine to replace Nashorn

### ISSUE THREAD

**Issue by ashvayka** [thingsboard/thingsboard#7505]
**Motivation**

ThingsBoard is written in Java, and currently is using Java 11. ThingsBoard uses JS user-defined functions in the Rule Engine and also in some PE components (Data Converters). There are two ways to execute the JS function in ThingsBoard: 
A) use remote JS Executor microservice written in Node.js. This is the default way for ThingsBoard to run in a cluster/microservices mode;
B) use local JS Executor powered by Nashorn JS engine that is running inside the JVM. This is the default way for ThingsBoard while deployed in monolithic mode.

The Nashorn JS engine is deprecated and will be removed from Java 16. It is also quite slow. That is why some of the users already called it the platform's kryptonite. 

The idea is to introduce an [MVEL](https://github.com/mvel/mvel) script executor that may substitute Nashorn and event Remote JS Executor in some cases. Few advantages of the MVEL:

1) MVEL is written in Java and is super fast comparing not Nashorn. For example, the execution of 1000 simple scripts like:
"return msg.temperature > 20" took 16s for Nashorn and 12ms for MVEL. More than 1000 times faster.
2) We have forked the MVEL codebase and added additional security improvements to ensure no CPU or memory abuse. So, no need to run Nashorn with the sandbox environment.
3) No latency compared to the Remote JS executor. The Remote executor is required to put a message to Kafka and process it in a separate service. Kafka introduces a relatively small latency (a few ms) but it may become a problem if you have multiple rule nodes chained into one rule chain. 
4) Easy to extend the list of available functions via Java code in the platform.

The plan is for MVEL and Remote JS executors to co-exist. Users will be able to choose whether to use MVEL (available everywhere) or Remote JS executors (available in [thingsboard.cloud](https://thingsboard.cloud) or any other cluster environments).

**Documentation**

MVEL Documentation is [here](https://en.wikibooks.org/wiki/Transwiki:MVEL_Language_Guide). There are some limitations compared to JS syntax but they are neglectable for 99% of use cases. If you can't use MVEL you always have the option to use a remote JS executor.

**Security**

We have forked the MVEL codebase and added additional security improvements to ensure no CPU or memory abuse. For example, we track memory allocation. For this purpose, we do not allow to create of instances of collections or other complex objects directly via `new` keyword or static factory methods. However, you may create inline lists and maps using [inline syntax](https://en.wikibooks.org/wiki/Transwiki:MVEL_Language_Guide#Inline_List,_Maps_and_Arrays). This is done because we substitute the default implementation of List and Map to track memory allocation. Please note that the calculation of memory allocation is not accurate. We have sacrificed accuracy in favor of performance. Use `MVEL_MAX_MEMORY_LIMIT_MB` to configure the max allocated memory and `MVEL_MAX_REQUEST_TIMEOUT` to configure the execution time.

**Configuration**

This feature is in Beta so you can completely disable the MVEL support using `MVEL_ENABLED` env variable. Additional configuration parameters are listed below:

```
mvel:
  enabled: "${MVEL_ENABLED:true}"
  max_total_args_size: "${MVEL_MAX_TOTAL_ARGS_SIZE:100000}"
  max_result_size: "${MVEL_MAX_RESULT_SIZE:300000}"
  max_script_body_size: "${MVEL_MAX_SCRIPT_BODY_SIZE:50000}"
  # Maximum allowed MVEL script execution memory
  max_memory_limit_mb: "${MVEL_MAX_MEMORY_LIMIT_MB: 8}"
  # Maximum allowed MVEL script execution errors before it will be blacklisted
  max_errors: "${MVEL_MAX_ERRORS:3}"
  # MVEL Eval max request timeout in milliseconds. 0 - no timeout
  max_requests_timeout: "${MVEL_MAX_REQUEST_TIMEOUT:500}"
  # Maximum time in seconds for black listed function to stay in the list.
  max_black_list_duration_sec: "${MVEL_MAX_BLACKLIST_DURATION_SEC:60}"
  # Specify thread pool size for javascript executor service
  thread_pool_size: "${MVEL_THREAD_POOL_SIZE:50}"
  stats:
    enabled: "${TB_MVEL_STATS_ENABLED:false}"
    print_interval_ms: "${TB_MVEL_STATS_PRINT_INTERVAL_MS:10000}"
```
