### ISSUE TITLE
[Bug] changing env variable HTTP_BIND_PORT breaks thingsboard

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#7539]
**Describe the bug**
In order to workaround the issue, that my tb currently cannot export reports, 
I need to try changing the port which tb is bound to. 

I looked up how to do this, and the docs said I can do it by adding env variables to my docker-compose.
originally I wanted to directly bind it to port 443 (since I have a proxy in front anyway (traefik)).
That did not work. 

Then I tried setting:

    environment:
      HTTP_BIND_ADDRESS: "0.0.0.0"
      HTTP_BIND_PORT: 8080

which also did not work. That is very werid do since this should be the default settings anyway.

The concrete problem: 

during startup (docker-compose up) the logs will say:

2022-11-03 11:37:33,903 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-0.0.0.0-8080"]
2022-11-03 11:37:33,906 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
2022-11-03 11:37:33,917 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

... shut down some tasks ...

***************************
APPLICATION FAILED TO START
***************************

Description:
Web server failed to start. Port 443 was already in use.
Action:
Identify and stop the process that's listening on port 443 or configure this application to listen on another port.

**Server Environment**
docker deployment 3.3.4.1PE

**Client Environment**
Desktop:
OS: Win 10
Browser chrome
Version 101.0.4951.67

**To Reproduce**
1. Open docker-compose.yml
2. add the env variables:

    environment:
      HTTP_BIND_ADDRESS: "0.0.0.0"
      HTTP_BIND_PORT: 8080

4. docker-compose up
5. 

**Expected behavior**
I expected the setting of 

    environment:
      HTTP_BIND_ADDRESS: "0.0.0.0"
      HTTP_BIND_PORT: 8080

to have no effect, because it is the default setting. (tb should work normally)

I expected the setting of 

    environment:
      HTTP_BIND_ADDRESS: "0.0.0.0"
      HTTP_BIND_PORT: 443

to make tb accessible via https://localhost:443 (I have a router that handles the encription and routs https://URL:443 to this service, so it should not matter on which port it is bound internally)

**Additional context**

The motivation for this is that I cannot export reports. I think this is due to the report servers public request being refused by thingsboard. Another user solved this by editing /etc/hosts. 

I tried adding 

0.0.0.0         webseiteURL 

to my /etc/hosts, so that no public request is being made, rather the report server should directly inquire with tb on the local server. 
Because I can export reports with the scheduler (where I can set with URL is being used) I am confident this can be a solution. 

However this did not fix the issue. My guess is that when a user exports via Dahboard UI, Thingsboard copies URL from browser and forwards it to tb-web-report. URL looks like this URL:443/something-something
hosts sees the URL and changes it to localhost:443/something-something

However tb sits on 8080. 

This should have been a quick fix, but it seems to be a broken feature.

**Comment by den1jkee** [comment]
Hi,
Could you please share your docker-compose.yml to review and explain in more detail why you are not doing it in traefik?
What happens with the web-reports?

**Comment by medutySMST** [comment]
For more details on the underlying problem with the web report, you can also read #6574. 

I am not sure what you mean by asking "explain in more detail why you are not doing it in traefik?". 

I am using traefik, it routes the different URLs to specific services, such as app1.baseurl.com to the service app1 in a docker container (eg. thingsboard). 

However since Thingsboard inside of its container also has a bind Port, because of cirumstances explained I need to change that.

My current setup is as follows; 

traefik routes tb.url.com requests to tb_container:8080. 

I have a basic docker-compose setup, see:

```
version: '2.2'
services:
  tb_red:
    container_name: tb_red
    restart: always
    image: store/thingsboard/tb-pe:3.3.4.1PE
    ports:
      - "31883:1883"
      - "35683:5683/udp"
    environment:
#      HTTP_BIND_ADDRESS: "0.0.0.0"
#      HTTP_BIND_PORT: 8080
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: secret
      TB_LICENSE_SECRET: secret
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      REPORTS_SERVER_ENDPOINT_URL: http://localhost:8383 # http://tb-web-report:8383 (tried to put tb-web-report into specific container )
      MQTT_MSG_QUEUE_SIZE_PER_DEVICE_LIMIT: 250
    volumes:
      - ./red_data:/data
      - ./red_data/hosts:/etc/hosts    # tried adding the line "0.0.0.0 tb.url.com" to etc/hosts to avoid firewall issues but creates explained issue, because user request comes from 'tb.url.com:443' tb-web-report tries to open dashbaord in 0.0.0.0:443, but tb is located at 0.0.0.0:8080. (however because of how web-report reads URL from browser If I avoid traefik, setup a direct port forwarding like this: url.com:8080 to tbcontainer:8080 this solution works but no https encryption(!) )
      - ./red_data/report_conf.yml:/usr/share/tb-web-report/conf/default.yml  # just edit wait time to avoid blank reports
      - ./red_logs:/var/log/thingsboard
    networks:
      - proxy
      - tb-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tb_red.entrypoints=websecure"
      - "traefik.http.routers.tb_red.rule=Host(`tb.url.com`)"
      - "traefik.http.routers.tb_red.tls.certresolver=httpresolver"
      - "traefik.http.services.tb_red.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
  
  postgres:
    restart: always
    image: "postgres:12"
    container_name: tb_red_db
    ports:
    - "5432"
    - "35432:5432"
    environment:
      POSTGRES_DB: secret
      POSTGRES_PASSWORD: secret
    volumes:
      - ./red_data/db:/var/lib/postgresql/data
    networks:
      - proxy
      - tb-web

networks:
  proxy:
    external: true
  tb-web:
    external: true
```

Now I have the following problem: 

- if I use traefik normally and don't edit etc/hosts inside tb_container, everythings works but tb-web-report cannot create reports via UI Button  (via scheduler works because I can type in to use tb.url.com ) (error is time out)
- if I try to solve this by not using traefik and doing direct port forwarding, the etc/hosts solution works, and I can do reports, but I will have to think of another https solution 
- if I try to use traefik and use the etc/hosts solution the reporting does not work (error is no body), I guess because the url:port does not route to tb instance (as explained above)
- if I try to use traefik and use the etc/hosts solution I can try and fix this solution by forcing tb inside of the container to be bound to port 443 (_maybe_). 

Hopefully I answered your question I am lost and I need help big time.
