### ISSUE TITLE
Image Map - Disable Dragging/Moving Image [Bug] 

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/thingsboard#7617]
We have been having issues using the image map of ThingsBoard Version 3.

![image](https://user-images.githubusercontent.com/108116747/201868993-c99e0fff-785f-49a8-8d06-3f0c01923466.png)

The image map loads perfectly when you open the dashboard, the problem is that you can move the image with your mouse.
Notice in the screenshot the image is off? this is because the user is able to click and drag the image.

Any workarounds or way to solve this issue?

Expected output:
The Image should be locked into place, user must not be able to drag the image.

**Comment by Chinmaya56789** [comment]
can i work on this ?

**Comment by ssakharova** [comment]
Hello @rajSilikon, @Chinmaya56789, 

There is no way to disable dragging in Image Map using the default functionality of the Thingsboard. However, you can try to use the following CSS snippet in Widget Settings → Widget Card → Card Style → Advanced Widget Style → Widget CSS:

```css
.leaflet-grab {
 cursor: default !important;
}
.leaflet-pane.leaflet-map-pane {
 transform: none !important;
}
```
