### ISSUE TITLE
[Bug] Version control unable to handle large number of objects

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#7733]
**Describe the bug**
Trying to use [version control](https://thingsboard.io/docs/user-guide/version-control/) feature to migrate assets and devices from one instance of TB to another.
I have 15k devices and 20k assets to migrate.

**Your Server Environment**
* own setup
  * Docker [setup](https://thingsboard.io/docs/user-guide/install/docker/)
  * ThingsBoard Version: 3.4.1
  * OS Name and Version: Ubuntu 20.04

**To Reproduce**
1. Prepare a TB instance with 15k devices and 20k assets.
2. Increase SPRING_MVC_ASYNC_REQUEST_TIMEOUT to more than enough to get over 500 timeout, default 30s is too short.
3. POST /api/entities/vc/version request:
```
{"branch":"release2","versionName":"da","syncStrategy":"MERGE","entityTypes":{"DEVICE":{"syncStrategy":null,"saveRelations":true,"saveAttributes":true,"saveCredentials":true,"allEntities":true}},"type":"COMPLEX"}
```
Response is 200 with a UUID string.

4. GET /api/entities/vc/version/<uuid>/status
Response is 200 with
```
{"version":null,"added":0,"modified":0,"removed":0,"error":"java.lang.RuntimeException: Future is already done!","do
```

**Expected behavior**
Should commit all devices and assets successfully to git repo.

**Comment by Raven888888** [comment]
@den1jkee 
No it does not help, I have set to
```
CACHE_SPECS_VERSION_CONTROL_TASK_TTL:60
CACHE_SPECS_VERSION_CONTROL_TASK_MAX_SIZE:500000
```
and docker compose down up TB.

Same response `Future is already done!`

**Comment by den1jkee** [comment]
Hi,
As I can see that this response is an exception to `request.getTimeoutTask()`
So there is a section in thingsboard.yml for VC with these parameters.
`````
vc:
    topic: "${TB_QUEUE_VC_TOPIC:tb_version_control}"
    partitions: "${TB_QUEUE_VC_PARTITIONS:10}"
    poll-interval: "${TB_QUEUE_VC_INTERVAL_MS:25}"
    pack-processing-timeout: "${TB_QUEUE_VC_PACK_PROCESSING_TIMEOUT_MS:60000}"
    request-timeout: "${TB_QUEUE_VC_REQUEST_TIMEOUT:60000}"
    msg-chunk-size: "${TB_QUEUE_VC_MSG_CHUNK_SIZE:250000}"
`````
If you get timeout by request, so try to increase this value, for example, for 10 min:
`````
TB_QUEUE_VC_REQUEST_TIMEOUT:600000
`````
Also, you can try to increase other values if this doesn`t help you.
Don`t forget to give us feedback. Thank you!
Best regards,
Denys.
