### ISSUE TITLE
[Question] Deploying Thingsboard on ECS

### ISSUE THREAD

**Issue by DEV-ONI** [thingsboard/thingsboard#7928]
Installation

**Description**
We are attempting to deploy Thingsboard on ECS Fargate instead of an EKS, using the docker-compose file described in `https://thingsboard.io/docs/user-guide/install/docker/`, are there any users who have taken a similar approach? We are attempting to deploy it on ECS, but would appreciate discussion on pointers or caveats we may not be aware of.

**Environment**
 Deployment on Amazon ECS using docker compose 
 * ThingsBoard: version 3.4.3

**Comment by DEV-ONI** [comment]
I am attempting the deployment with this config 


```
version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
```

I needed to change the port mapping as ECS Fargate does not support asymmetrical port mapping(?)

but seem to be getting this error

```
Invalid request provided: CreateService error: load balancers can have at most 5 items. (Service: AmazonECS; Status Code: 
400; Error Code: InvalidParameterException; Request ID: 61079890-20bc-4c19-aef9-4b6da651d9ea; Proxy: null)
```
