### ISSUE TITLE
Unable to connect to ThingsBoard

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#816]
I have problems connecting the ThingsBoard IoT Gateway to the live demo server.
The following error messages are present in the tb-gateway.log file:

```
2018-05-30 15:53:41,215 [main] INFO  o.t.g.s.DefaultTenantManagerService - [Tenant] Initializing gateway
2018-05-30 15:53:52,469 [main] ERROR o.t.g.s.gateway.MqttGatewayService - Unable to connect to ThingsBoard. Connection timed out after [10000] milliseconds
```

This is what I have in the tb-gatewa.yml file:

```
gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "demo.thingsboard.io"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "xxxxx"
      remoteConfiguration: false
      extensions:
        -
          id: "mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config.json
```

Any ideas why this does not work?

**Comment by ashvayka** [comment]
Hi! Please share mqtt-config.json. Are you sure you have configured the device as a gateway (checkbox in device details)?

**Comment by abrasat** [comment]
I dont have right now access to the project, I will share it as soon as possible.
Why does the connection between tb gateway and Thingboard server depend on the mqtt-json configuration?
If thingboard is started locally (instead of using the live demo server), is it still possible to visualize mqtt values on the web dashboard ?

**Comment by vparomskiy** [comment]
Sure, Thingsboard can visualize any data that was submitted.

**Comment by abrasat** [comment]
Ok, thx. I am just starting to learn how to work with Thingsboard.
My actual use-case is an embedded device publishing mqtt data to a mosquitto broker. I would like to use the Thingsboard dashboard to subscribe to these mqtt topics from the mosquitto broker, and to visualize them with different widgets.
Is there anywhere available a description about how to configure the different thingsboard files and devices on dashboard for this scenario ?

**Comment by mp-loki** [comment]
https://thingsboard.io/docs/iot-gateway/getting-started/#step-8-connect-to-external-mqtt-broker

**Comment by abrasat** [comment]
Thx for link.
Does the "IsGateway" checkbox always have to be set for the device when using IoT gateway to external Mqtt broker?
And what configuration has to changed when using local Thingboard server instead of live demo server, besides changing the host for "connection" entry in the tb-gateway.yml file ?

```
      connection:
        host: localhost
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "xxxxx"
      remoteConfiguration: false
```
Does the access token always have be set ?
