### ISSUE TITLE
[Feature Request] SSL for Kafka Connection

### ISSUE THREAD

**Issue by FawenYo** [thingsboard/thingsboard#8230]
Hi, I'm attempting to utilize Kafka as a queue service for Thingsboard. 
I have already created my Kafka with Bitnami packaged version ([charts/bitnami/kafka at main · bitnami/charts (github.com)](https://github.com/bitnami/charts/tree/main/bitnami/kafka)) and enable SSL/TLS (`auth.clientProtocol`: tls).
However, when I tried to start up Thingsboatd, it just kept crashing because it couldn't list Kafka topics. At the same time, I saw the following error logs in Kafka:

```
Failed authentication with /${IP} (channelId=${IP}:9092-${IP}:47112-183) (SSL handshake failed)
```

I looked through the configuration docs of the Thingsboard ([Configuration properties | ThingsBoard Community Edition](https://thingsboard.io/docs/user-guide/install/config/#queue-parameters)) but found no configuration for Kafka SSL option.
I also took a quick look at the code and found that Thingsboard seems to not support Kafka SSL for now (e.g. [thingsboard/kafkaTemplate.ts at 1be933622db1157f79a2d790e5547984344c7387 · thingsboard/thingsboard (github.com)](https://github.com/thingsboard/thingsboard/blob/1be933622db1157f79a2d790e5547984344c7387/msa/js-executor/queue/kafkaTemplate.ts#L69-L73)).

Could you please add a feature for Kafka SSL option? Thanks!

**Comment by ban2derlog** [comment]
hi, thingsboard can work with kafka+ssl.
in configuration this use _**confluent**_ sub name, but don't let this confuse you.
test these parameters with clonfluent=true feature and configure ThingsBoard to work with your Kafka service\cluster.
example:

    @Value("${queue.kafka.confluent.ssl.algorithm}")
    private String sslAlgorithm;

    @Value("${queue.kafka.confluent.sasl.mechanism}")
    private String saslMechanism;

    @Value("${queue.kafka.confluent.sasl.config}")
    private String saslConfig;

    @Value("${queue.kafka.confluent.security.protocol}")
    private String securityProtocol;
--------------------------------------
        if (useConfluent) {
            props.put("ssl.endpoint.identification.algorithm", sslAlgorithm);
            props.put("sasl.mechanism", saslMechanism);
            props.put("sasl.jaas.config", saslConfig);
            props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, securityProtocol);
        }
`

**Comment by FawenYo** [comment]
Hi @ban2derlog, I tested the environment variable `TB_QUEUE_KAFKA_USE_CONFLUENT_CLOUD` to `true`, but I still get the SSL handshake error with the message
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by FawenYo** [comment]
Hi @smatvienko-tb , thanks for your advice.

But in `TbKafkaSettings` it didn't import `org.apache.kafka.common.config.SslConfigs`, I think it is not possible to use some SSL settings such as 
```
props.put(SslConfigs.SSL_TRUSTSTORE_LOCATION_CONFIG, sslTruststoreLocation);
```
?

**Comment by smatvienko-tb** [comment]
Additional Kafka client parameters:
https://kafka.apache.org/documentation/#security_configclients

**Comment by smatvienko-tb** [comment]
> Hi, thanks for your help!
> 
> I didn't find your mentioned code in the thingsboard project `public static final String SSL_TRUSTSTORE_LOCATION_CONFIG = "ssl.truststore.location";` Can you please give a hint of the line number of the code?

Hi! 
Just drill down the constant (`Ctrl+B` for my IntelliJ Idea)
```
package org.apache.kafka.common.config;
public class SslConfigs {
public static final String SSL_TRUSTSTORE_LOCATION_CONFIG = "ssl.truststore.location";

```

> 
> Besides, I checked the yaml file you mentioned, so in that way I still need to modify the yaml and build the docker image myself? Or I can just set some environment variable to Docker environment variable?

You need to map a custom yaml file with a standard docker image. After that, you will be able to apply new environment variables.
Or inject your customer lines to the YAML with init container in Kubernetes. Or use a custom init script.  

Yes, it's not super easy for future updates. But the scope of work is minimal compared to custom build.

**Comment by FawenYo** [comment]
Hi @smatvienko-tb, so I tried to use `volumeMount` to mount the YAML file to `/usr/share/thingsboard/conf/thingsboard.yml`, and here is part of my modified YAML

```
other: # In this section you can specify custom parameters for Kafka consumer/producer and expose the env variables to configure outside
  - key: "request.timeout.ms" # refer to https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_request.timeout.ms
    value: "${TB_QUEUE_KAFKA_REQUEST_TIMEOUT_MS:30000}" # (30 seconds)
  - key: "session.timeout.ms" # refer to https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_session.timeout.ms
    value: "${TB_QUEUE_KAFKA_SESSION_TIMEOUT_MS:10000}" # (10 seconds)
  #TODO: Wait Thingsboard to add SSL option in future build. Below part is self-added code
  - key: "security.protocol"
    value: "${TB_KAFKA_PROTOCOL:none}"
  - key: "ssl.truststore.location"
    value: "${TB_KAFKA_SSL_TRUSTSTORE_LOCATION:none}"
  - key: "ssl.truststore.password"
    value: "${TB_KAFKA_SSL_TRUSTSTORE_PASSWORD:none}"
  - key: "ssl.keystore.location"
    value: "${TB_KAFKA_SSL_KEYSTORE_LOCATION:none}"
  - key: "ssl.truststore.password"
    value: "${TB_KAFKA_SSL_KEYSTORE_PASSWORD:none}"
  - key: "ssl.key.password"
    value: "${TB_KAFKA_SSL_KEY_PASSWORD:none}"
```

And I set the value with

```
- name: TB_KAFKA_PROTOCOL
  value: "SSL"
- name: TB_KAFKA_SSL_TRUSTSTORE_LOCATION
  value: /etc/thingsboard/conf/jks/{{ .Values.jks.truststore_name }}
- name: TB_KAFKA_SSL_TRUSTSTORE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.jks.secret_name }}
      key: {{ .Values.jks.truststore_password_name }}
- name: TB_KAFKA_SSL_KEYSTORE_LOCATION
  value: /etc/thingsboard/conf/jks/{{ .Values.jks.keystore_name }}
- name: TB_KAFKA_SSL_KEYSTORE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.jks.secret_name }}
      key: {{ .Values.jks.keystore_password_name }}
- name: TB_KAFKA_SSL_KEY_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.jks.secret_name }}
      key: {{ .Values.jks.keystore_password_name }}
```

But after modified the pod still keep restarting, below is the error log. Do I missed some settings? 

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/40032648/227459397-de3b49d3-86fe-4f6a-bee6-ecf6a738eed0.png">
