### ISSUE TITLE
[Question] Windows run install.bat successful, but CentOS7 run install.sh failed

### ISSUE THREAD

**Issue by wushuaiping** [thingsboard/thingsboard#8875]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
The same configuration works successfully on Windows 11, but fails on Cent OS 7
Windows 11, update file: thingsboard.yml
```
........
database:
  ts_max_intervals: "${DATABASE_TS_MAX_INTERVALS:700}" # Max number of DB queries generated by single API call to fetch telemetry records
  ts:
    type: "${DATABASE_TS_TYPE:timescale}" # cassandra, sql, or timescale (for hybrid mode, DATABASE_TS_TYPE value should be cassandra, or timescale)
  ts_latest:
    type: "${DATABASE_TS_LATEST_TYPE:timescale}" # cassandra, sql, or timescale (for hybrid mode, DATABASE_TS_TYPE value should be cassandra, or timescale)
.......
# SQL DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    properties:
      javax.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}"
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.1.8:5432/thingsboard}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:123456}"
    hikari:
      leakDetectionThreshold: "${SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD:0}"
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:16}"
      registerMbeans: "${SPRING_DATASOURCE_HIKARI_REGISTER_MBEANS:false}" # true - enable MBean to diagnose pools state via ........
``` 
run install.bat:
![image](https://github.com/thingsboard/thingsboard/assets/26813459/d6d3232b-163f-4078-9401-cf2d7df5ec66)

CentOS 7, update file: thingsboard.conf
![image](https://github.com/thingsboard/thingsboard/assets/26813459/18493c56-8395-49a5-8865-5f0440fe47c1)

get error:
![image](https://github.com/thingsboard/thingsboard/assets/26813459/2ed0208f-c3ed-41bc-b406-15419b836066)

cat /var/log/thingsboard/install.log:
![image](https://github.com/thingsboard/thingsboard/assets/26813459/61c4d0b5-d90b-4c75-8e60-6751323d3310)
![image](https://github.com/thingsboard/thingsboard/assets/26813459/bf5a14c2-62b0-428a-ba4c-5ef9d83efb7f)
![image](https://github.com/thingsboard/thingsboard/assets/26813459/2db89452-defd-41de-b3a9-9aea62ef207f)

can you help me ? thanks!
**Environment**

 * OS:  Cent OS 7
 * ThingsBoard: 3.5.1 master branch
 * Browser: name and version
