### ISSUE TITLE
POST: /api/noauth/oauth2Clients?platform=WEB 404: Not Found

### ISSUE THREAD

**Issue by T1-leiyang** [thingsboard/thingsboard#9230]
![image](https://github.com/thingsboard/thingsboard/assets/46803133/4842aed2-4e31-432d-b25f-802e2127ae72)

k8s version: 1.18
helm version: v3.9.4
通过helm repo add thingsboard https://midokura.github.io/thingsboard-ce-k8s 部署了最新的版本
访问报错如图

**Comment by filouz** [comment]
It appears that the issue you're experiencing is due to the version of Traefik and its handling of regex paths for URL forwarding. 


### Option 1: Update Helm Chart (templates/ingress.yaml)

```yaml
...
- host: {{ . | quote }}
  http:
    paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-http
            port:
              number: {{ $values.http.service.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /webjars
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /v3
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /static/rulenode
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /assets/help/rulenode # TODO: /assets/help/.*/rulenode/.*
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /login/oauth2
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-node
            port:
              number: {{ $values.node.service.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-webui
            port:
              number: {{ $values.webui.service.port }}
...
```

### Option 2: Downgrade to Traefik 1.xx

Downgrading to Traefik version 1.xx should align with your current setup and how regex paths are managed.
