### ISSUE TITLE
[Question] Thingsboard installation failed with external database (docker-compose)

### ISSUE THREAD

**Issue by nomanuser** [thingsboard/thingsboard#9420]
Hi,
i'm triying to install thingsboard with external database, i'm making a test to later make on production.
1. I install thingsboard with docker-compose with postgres in the same container.
`version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory

    volumes:
      - ./logs/mytb-data:/data
      - ./logs/mytb-logs:/var/log/thingsboard
`
`
mkdir -p ./logs/mytb-data && sudo chown -R 799:799 ./logs/mytb-data
mkdir -p ./logs/mytb-logs && sudo chown -R 799:799 ./logs/mytb-logs
`

2. I install a postgres container and create "thingsboard" database.
`
version: '3.0'
services:
  db:
    image: postgres:12-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pg12-data:/var/lib/postgresql/data
`

3. I make a little changes in the docker-compose of thingsboard
`
version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres12-docker-compose_db_1:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - /path-pgsql/pg12-data/db:/data
      - ./logs/mytb-logs:/var/log/thingsboard
`

When i run the docker-compose of thingsboard once again i have this error:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
mytb_1  | ERROR: ThingsBoard is not installed

**Comment by ttqteo** [comment]
This issue causes because your Thingsboard cannot connect to your database.
And root cause is your containers not in the same network.

We have 2 ways to solve this:
1. Bring all containers into a docker-compose. Below is reference:
```yaml
version: '3.0'
services:
  postgresdb:
    restart: on-failure
    image: postgres:12
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    user: "799:799"
    volumes:
      - ./.mytb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cloud:
    restart: on-failure
    platform: linux/amd64
    image: thingsboard/tb-postgres
    user: "799:799"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp" 
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./.mytb-data:/data
      - ./.mytb-logs:/var/log/thingsboard
    depends_on:
      - postgresdb
```

2. You should set up your external network
```yaml
networks:
  default:
    external:
      name: <your-network>
```
